import { randomUUID } from "node:crypto";
import { IntentLink as Link } from "@/components/layout/intent-link";
import { uuidSchema } from "@nognog/domain";
import { notFound } from "next/navigation";
import { CancelPurchaseOrderForm, ReceivePurchaseLineForm, RecordSupplierPaymentForm, VoidSupplierPaymentForm } from "@/components/purchase-orders/purchase-order-forms";
import { RecordCreateDialog } from "@/components/ui/record-create-dialog";
import { Button } from "@/components/ui/button";
import { DataTableShell } from "@/components/ui/data-table-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { tableHeadClass } from "@/components/ui/table-sort-heading";
import { requireProcurementViewer } from "@/lib/auth";
import { getPurchaseOrder, getPurchaseOrderPayments } from "@/lib/data/purchase-orders";

const money = (amount: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(amount);

const postedMessages: Record<string, string> = { receipt: "Delivery received. The stock is now in the warehouse.", cancelled: "Purchase order cancelled.", payment: "Payment saved.", "payment-void": "Payment voided.", "owner-approved": "Owner approval recorded. The purchase order is now issued." };

export default async function PurchaseOrderPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ posted?: string; action?: string; line?: string }> }) {
  const user = await requireProcurementViewer();
  const id = (await params).id;
  if (!uuidSchema.safeParse(id).success) notFound();
  const [{ order, approval, lines, receipts }, payments] = await Promise.all([getPurchaseOrder(id), getPurchaseOrderPayments(id)]);
  const orderTotal = lines.reduce((sum, line) => sum + Math.round(Number(line.ordered_quantity) * Number(line.unit_price) * 100) / 100, 0);
  const query = await searchParams;
  const posted = query.posted;
  const today = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Manila", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  return <>
    <PageHeader title={order.po_number} description={`${order.supplier_name} · ${order.warehouse_name}`} action={<Button variant="outline" asChild><Link href="/purchase-orders">Back to purchases</Link></Button>} />
    {posted && postedMessages[posted] && <p role="status" className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{postedMessages[posted]}</p>}
    <section className="mt-7 rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">{order.purpose && <p className="mb-2 font-medium text-slate-900">{order.purpose}</p>}<p>Purchased {order.ordered_on}{order.expected_on ? ` · Expected ${order.expected_on}` : ""} · <span className="capitalize">{order.status.replaceAll("_", " ")}</span></p>{approval && <p className="mt-2">Owner approved {approval.decided_at ? new Date(approval.decided_at).toLocaleDateString("en-PH", { timeZone: "Asia/Manila" }) : ""} · <Link href={`/purchase-orders/approvals/${approval.id}`} className="text-cyan-700 hover:underline">View approval</Link></p>}{order.cancellation_reason && <p className="mt-2">Cancellation: {order.cancellation_reason}</p>}</section>
    <h2 className="mt-8 text-lg font-semibold text-slate-900">Purchased materials</h2>
    <DataTableShell footer={<div className="flex w-full items-center justify-between text-sm"><span className="text-xs text-slate-500">{lines.length} item{lines.length === 1 ? "" : "s"}</span><span>Total <span className="ml-3 font-semibold tabular-nums text-slate-900">{money(orderTotal)}</span></span></div>}><table className="w-full min-w-[690px] text-left text-sm"><thead className={tableHeadClass}><tr><th className="px-5 py-3">Item</th><th className="px-4 py-3 text-right">Quantity</th><th className="px-4 py-3 text-right">Received</th><th className="px-4 py-3 text-right">Price</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-100">{lines.map((line) => <tr key={line.id}><td className="px-5 py-4"><p className="font-medium text-slate-800">{line.material_name}</p><p className="text-xs text-slate-500">{line.material_code}</p></td><td className="px-4 py-4 text-right tabular-nums">{line.ordered_quantity} {line.unit_symbol}</td><td className="px-4 py-4 text-right tabular-nums">{line.received_quantity} {line.unit_symbol}</td><td className="px-4 py-4 text-right tabular-nums">{money(line.unit_price)}</td><td className="px-5 py-4 text-right font-medium tabular-nums">{money(Math.round(Number(line.ordered_quantity) * Number(line.unit_price) * 100) / 100)}</td></tr>)}</tbody></table></DataTableShell>
    {payments && <section className="mt-8" id="supplier-payments" aria-labelledby="payments-heading">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="payments-heading" className="text-lg font-semibold text-slate-900">Supplier Payment</h2><p className="mt-1 text-sm text-slate-600">Total {money(payments.total)} · Paid {money(payments.paid)} · <span className={payments.balance > 0 ? "font-semibold text-amber-700" : "font-semibold text-emerald-700"}>{payments.balance > 0 ? `Balance ${money(payments.balance)}` : "Fully paid"}</span></p></div>
        {user.canViewLaborRates && order.status !== "cancelled" && payments.balance > 0 && <RecordCreateDialog title="Supplier Payment" triggerLabel="Supplier Payment" initialOpen={query.action === "payment"} closeHref={`/purchase-orders/${id}`}><RecordSupplierPaymentForm orderId={id} balance={payments.balance} idempotencyKey={randomUUID()} today={today} /></RecordCreateDialog>}</div>
      <DataTableShell empty={payments.payments.length === 0 ? <EmptyState compact title="No payments yet" description="Record a cash or check payment for this purchase." /> : undefined}><table className="w-full min-w-[720px] text-left text-sm"><thead className={tableHeadClass}><tr><th className="px-5 py-3">Term</th><th className="px-4 py-3">Bank</th><th className="px-4 py-3">Check no.</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Amount</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.payments.map((payment) => <tr key={payment.id} className={payment.voidReason ? "text-slate-400" : undefined}><td className="px-5 py-4 capitalize">{payment.method}{payment.remarks && <p className="text-xs normal-case text-slate-500">{payment.remarks}</p>}</td><td className="px-4 py-4">{payment.bank_name ?? "—"}</td><td className="px-4 py-4 tabular-nums">{payment.check_number ?? "—"}</td><td className="px-4 py-4 tabular-nums">{payment.payment_date}</td><td className={`px-4 py-4 text-right tabular-nums ${payment.voidReason ? "line-through" : "font-medium"}`}>{money(payment.amount)}</td><td className="px-5 py-4 text-xs">{payment.voidReason ? <span>Void · {payment.voidReason}</span> : payment.method === "check" && payment.payment_date > today ? <span className="rounded-full bg-amber-50 px-2 py-0.5 font-semibold text-amber-700">Postdated</span> : <span className="text-slate-500">Paid{payment.recordedByName ? ` · ${payment.recordedByName}` : ""}</span>}{!payment.voidReason && user.canManage && <span className="ml-2"><RecordCreateDialog title="Void payment" triggerLabel="Void" triggerVariant="ghost"><p className="mb-4 text-sm text-slate-600">{payment.method === "check" ? `Check ${payment.check_number} · ${payment.bank_name}` : "Cash"} · {money(payment.amount)}</p><VoidSupplierPaymentForm orderId={id} paymentId={payment.id} /></RecordCreateDialog></span>}</td></tr>)}</tbody></table></DataTableShell>
    </section>}
    {user.canManage && ["issued", "partially_received"].includes(order.status) && <section className="mt-8"><h2 className="text-lg font-semibold text-slate-900">Receive a delivery</h2><p className="mt-1 text-xs text-slate-500">You can receive part of an order now and the rest later. Each delivery becomes its own price batch.</p><div className="mt-4 grid gap-4">{lines.filter((line) => line.ordered_quantity > line.received_quantity).map((line) => {
      const initialOpen = query.action === "receive" && query.line === line.id;
      return <div key={line.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm">{line.material_code} · {line.material_name} · {line.ordered_quantity - line.received_quantity} {line.unit_symbol} remaining</p><RecordCreateDialog key={`${line.id}:${line.received_quantity}`} title="Record delivery" triggerLabel="Receive" triggerVariant="outline" initialOpen={initialOpen} closeHref={`/purchase-orders/${id}`}><ReceivePurchaseLineForm orderId={id} lineId={line.id} remaining={line.ordered_quantity - line.received_quantity} unitPrice={line.unit_price} unitSymbol={line.unit_symbol} idempotencyKey={randomUUID()} today={today} /></RecordCreateDialog></div>;
    })}</div></section>}
    <h2 className="mt-8 text-lg font-semibold text-slate-900">Receipt history</h2>
    <DataTableShell empty={receipts.length === 0 ? <EmptyState compact title="No deliveries recorded" description="Post a delivery from an outstanding order line." /> : undefined} footer={<span className="text-xs text-slate-500">{receipts.length} receipt{receipts.length === 1 ? "" : "s"}</span>}><table className="w-full min-w-[650px] text-left text-sm"><thead className={tableHeadClass}><tr><th className="px-5 py-3">Delivery reference</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Quantity</th><th className="px-4 py-3 text-right">Goods cost</th><th className="px-5 py-3">Variance</th></tr></thead><tbody className="divide-y divide-slate-100">{receipts.map((receipt) => <tr key={receipt.id}><td className="px-5 py-4 font-medium text-slate-800">{receipt.delivery_reference}</td><td className="px-4 py-4">{receipt.received_on}</td><td className="px-4 py-4 text-right">{receipt.quantity}</td><td className="px-4 py-4 text-right">{money(receipt.goods_total_cost)}</td><td className="px-5 py-4 text-xs text-slate-500">{receipt.correctionReason ? <span>Reversed · {receipt.correctionReason}</span> : <>{receipt.cost_variance_reason ?? "—"}{user.canManage && <Link className="ml-2 text-cyan-700" href={`/inventory/transactions?reverse=${receipt.inventory_transaction_id}`}>Correct receipt</Link>}</>}</td></tr>)}</tbody></table></DataTableShell>
    {user.canManage && order.status === "issued" && <details className="mt-6 max-w-md rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm font-medium text-slate-700">Cancel order</summary><div className="mt-4"><CancelPurchaseOrderForm orderId={id} /></div></details>}
  </>;
}
