import { PhotoViewer } from "@/components/ui/photo-viewer";
import { Button } from "@/components/ui/button";
import { RecordCreateDialog } from "@/components/ui/record-create-dialog";
import { MaterialForm } from "@/components/materials/material-form";
import { DataTableShell } from "@/components/ui/data-table-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { EntityQrSection } from "@/components/qr/entity-qr-section";
import { requireUser } from "@/lib/auth";
import { getMaterial, getMaterialCostBatches } from "@/lib/data/inventory";
import { archiveMaterialAction } from "../actions";
import { recordPhotoUrl } from "@/lib/media/record-photo-url";
const money = (amount: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(amount);
const ordinalSuffix = (value: number) => (value % 100 >= 11 && value % 100 <= 13 ? "th" : ["th", "st", "nd", "rd"][value % 10] ?? "th");
export default async function MaterialPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ edit?: string }> }) { const { id } = await params; const editing = (await searchParams).edit === "1"; const [user, data] = await Promise.all([requireUser(), getMaterial(id)]); const { material, category, unit, balances } = data; const batches = user.canViewLaborRates ? await getMaterialCostBatches(id) : null; return <>
  <PageHeader eyebrow={material.code} title={material.name} description={material.description || "Material master record"} action={user.canManage && <div className="flex gap-2"><RecordCreateDialog key={material.updated_at} title="Edit material" triggerLabel="Edit" triggerVariant="outline" initialOpen={editing} closeHref={`/materials/${id}`}><MaterialForm material={material} {...data.references} /></RecordCreateDialog><form action={archiveMaterialAction}><input type="hidden" name="id" value={id} /><Button variant="outline" type="submit">Archive</Button></form></div>} />
  {material.photo_path && <div className="relative mt-7 h-56 max-w-xl overflow-hidden rounded-xl bg-slate-100"><PhotoViewer src={recordPhotoUrl("materials", id, material.updated_at)} alt={`${material.name} photo`} sizes="(max-width: 640px) 100vw, 576px" /></div>}
  <dl className="mt-7 grid gap-x-8 gap-y-5 border-y border-slate-200 bg-white px-5 py-6 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-slate-400">Category</dt><dd className="mt-1 text-sm font-semibold">{category?.name ?? "Unavailable"}</dd></div><div><dt className="text-xs text-slate-400">Base unit</dt><dd className="mt-1 text-sm font-semibold">{unit ? `${unit.name} (${unit.symbol})` : "Unavailable"}</dd></div><div><dt className="text-xs text-slate-400">Minimum stock</dt><dd className="mt-1 text-sm font-semibold tabular-nums">{material.minimum_stock_level} {unit?.symbol}</dd></div><div><dt className="text-xs text-slate-400">Type / status</dt><dd className="mt-1 text-sm font-semibold capitalize">{material.material_kind} · {material.is_active ? "Active" : "Inactive"}</dd></div></dl>
  <EntityQrSection entityType="material" entityId={id} canManage={user.canManage} />
  <div className="mt-8"><h2 className="font-semibold">Stock by location</h2><p className="mt-1 text-xs text-slate-500">Available equals on hand minus reserved.</p></div>
  <DataTableShell empty={balances.length === 0 ? <EmptyState kind="items" title="No stock posted yet" description="Post a stock-in entry to start tracking this material." /> : undefined}><table className="w-full min-w-[620px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-5 py-3">Location</th><th className="px-4 py-3 text-right">On hand</th><th className="px-4 py-3 text-right">Reserved</th><th className="px-5 py-3 text-right">Available</th></tr></thead><tbody className="divide-y divide-slate-100">{balances.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="text-sm font-semibold">{item.location?.name ?? "Unavailable location"}</p><p className="text-[11px] text-slate-400">{item.location?.detail}</p></td><td className="px-4 py-4 text-right text-sm tabular-nums">{item.quantity_on_hand} {unit?.symbol}</td><td className="px-4 py-4 text-right text-sm tabular-nums">{item.reserved_quantity} {unit?.symbol}</td><td className="px-5 py-4 text-right text-sm font-semibold tabular-nums">{item.available_quantity} {unit?.symbol}</td></tr>)}</tbody></table></DataTableShell>
  {batches && <><div className="mt-8"><h2 className="font-semibold">Price batches</h2><p className="mt-1 text-xs text-slate-500">Each purchase keeps its own price. At each location the newest batch is used first, then the next newest.</p></div>
  <DataTableShell empty={batches.length === 0 ? <EmptyState kind="items" title="No priced stock" description="A batch appears when stock is received with a cost." /> : undefined}><table className="w-full min-w-[620px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-5 py-3">Location</th><th className="px-4 py-3">Order of use</th><th className="px-4 py-3">Batch</th><th className="px-4 py-3 text-right">Unit price</th><th className="px-4 py-3 text-right">Remaining</th><th className="px-5 py-3 text-right">Value</th></tr></thead><tbody className="divide-y divide-slate-100">{batches.map((batch) => <tr key={`${batch.location_id}-${batch.batch_number}`}><td className="px-5 py-4 text-sm font-semibold">{batch.location_name}</td><td className="px-4 py-4 text-sm">{Number(batch.use_order) === 1 ? <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-semibold text-emerald-700">Used next</span> : `${batch.use_order}${ordinalSuffix(Number(batch.use_order))}`}</td><td className="px-4 py-4 text-sm">{Number(batch.batch_number) === 0 ? "Carried forward" : `Received ${batch.batch_date}`}</td><td className="px-4 py-4 text-right text-sm tabular-nums">{money(Number(batch.unit_cost))}/{unit?.symbol}</td><td className="px-4 py-4 text-right text-sm tabular-nums">{batch.remaining_quantity} {unit?.symbol}</td><td className="px-5 py-4 text-right text-sm font-semibold tabular-nums">{money(Number(batch.remaining_value))}</td></tr>)}</tbody></table></DataTableShell></>}
  </>; }
