import { IntentLink as Link } from "@/components/layout/intent-link";
import { requireUser } from "@/lib/auth";
import { PageHeader } from "@/components/ui/page-header";

type Guide = { id: string; title: string; detail: string; href: string; steps: string[] };

export default async function HelpPage() {
  const user = await requireUser();
  const siteStaff = user.roles.some((role) => role === "engineer" || role === "foreman");
  const guides: Guide[] = [
    { id: "start", title: "Find your way around", detail: "Navigation, search and your account", href: "/dashboard", steps: ["Expand a sidebar category and choose a page. Use the project search in the header to find a project.", "Open your account menu to update your profile or sign out. Settings and Help centre are in the sidebar's Settings group.", "Only actions permitted for your account and assignments are shown."] },
    { id: "projects", title: "Projects and sites", detail: "Review work, progress and project costs", href: "/projects", steps: ["Open a project to review its Overview, Sites, Labour, Materials, Finance and Documents sections, subject to your access.", "Check the material plan for shortages before requesting stock or purchasing materials.", "Record actual progress in dated reports. A request or delivery is not material use or project cost."] },
    { id: "inventory", title: "Materials and inventory", detail: "Balances, locations and transaction history", href: "/inventory", steps: ["Choose a warehouse or project site to view stock balances for that location.", "Use Stock in/out or Transfers only when your role allows it. A transfer reduces source stock at dispatch and increases destination stock at receipt.", "Open History to trace stock movements; equipment and vehicles are separate from consumable materials."] },
    ...(user.canManage || user.canOperateInventory || siteStaff ? [{ id: "requests", title: "Material requests", detail: "Request, approve, dispatch, receive and use", href: "/requests", steps: ["Assigned site staff request material for a project site and specify the required quantity.", "The authorized reviewer approves the request; approval alone does not reduce warehouse stock.", "Warehouse staff dispatch approved stock, site staff confirm receipt, and actual site use posts the project material cost."] }] : []),
    ...(user.canViewProcurement ? [{ id: "purchases", title: "Suppliers and purchases", detail: "Prices, purchases and deliveries", href: "/suppliers", steps: ["Maintain suppliers, their materials and dated PHP prices.", "Create a purchase for a warehouse using the saved price for its purchase date.", "Record the actual delivered quantity and cost. A posted receipt updates stock value; changing a later quote does not rewrite past costs."] }] : []),
    ...(siteStaff || user.canManage ? [{ id: "reports", title: "Daily reports", detail: "Dated site updates", href: "/reports/daily", steps: ["Choose an assigned project and site, then enter the date and work summary.", "Review progress and any linked material or labour entries on the project pages.", "Do not count the same labour, equipment or material entry twice when reviewing project costs."] }] : []),
    ...(user.canManage ? [{ id: "access", title: "Users and audit history", detail: "Accounts, assignments and recorded changes", href: "/users", steps: ["Invite or manage the four supported account roles and assign their project or warehouse access.", "Use Audit logs to see who made recorded changes and when.", "For a denied operation, check the account's role and assignment rather than sharing another account."] }] : []),
    { id: "account", title: "Your account and notifications", detail: "Profile, alerts and appearance", href: "/profile", steps: ["Change your name, phone, email or profile photo in Settings. Email changes need confirmation.", "Open Notifications to review in-app alerts and mark them read.", "Use the appearance button to cycle through Light, Blue dark and Charcoal."] },
  ];
  return <div className="mx-auto max-w-3xl"><PageHeader title="Help centre" description="Short guides for the workflows available to your account." />
    <nav aria-label="Guide topics" className="mt-7 flex flex-wrap gap-2">{guides.map((guide) => <a key={guide.id} href={`#${guide.id}`} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:border-cyan-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-600">{guide.title}</a>)}</nav>
    <div className="mt-5 space-y-4">{guides.map((guide) => <section key={guide.id} id={guide.id} className="scroll-mt-28 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-900">{guide.title}</h2><p className="mt-1 text-sm text-slate-600">{guide.detail}</p></div><Link href={guide.href} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-medium text-cyan-700 hover:border-cyan-400">Open section →</Link></div><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-600">{guide.steps.map((step) => <li key={step}>{step}</li>)}</ol></section>)}</div>
  </div>;
}
