import { createClient } from "@/lib/supabase/server";
import { HistoryPagination } from "@/components/ui/history-pagination";
import { RecordCreateDialog } from "@/components/ui/record-create-dialog";
import { ReportResourceForm } from "./report-resource-form";
export async function ReportResourceSection({ reportId, linkedPage, candidatePage, candidatesOpen = false }: { reportId: string; linkedPage: number; candidatePage: number; candidatesOpen?: boolean }) {
  const db = await createClient();
  const load = (linked: boolean, page: number) => db.rpc("list_daily_report_resources", { p_report_id: reportId, p_linked: linked, p_offset: (page - 1) * 20, p_limit: 20 });
  const [linked, candidates] = await Promise.all([load(true, linkedPage), load(false, candidatePage)]);
  if (linked.error || candidates.error) throw new Error("Unable to load daily report resources.");
  const table = (rows: NonNullable<typeof linked.data>, picker: boolean) => <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Record", "Quantity / hours", "Status", "Cost", "Action"].map((label) => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={`${r.kind}-${r.resource_id}`} className="border-t border-slate-100"><td className="px-3 py-3">{r.label}<p className="text-xs text-slate-500">{r.kind}{!r.site_known && " · Historical site unknown"}</p></td><td className="px-3 py-3">{r.quantity} {r.unit}</td><td className="px-3 py-3">{r.reversed ? "Reversed · excluded" : "Posted"}</td><td className="px-3 py-3">{r.cost === null ? "Restricted" : r.reversed ? "—" : new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(r.cost)}</td>{<td className="px-3 py-3"><ReportResourceForm reportId={reportId} resourceId={r.resource_id} kind={r.kind} detach={!picker} /></td>}</tr>)}</tbody></table>{!rows.length && <p className="p-3 text-sm text-slate-500">No matching records on this page.</p>}</div>;
  return <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Material, labor & equipment records</h2><RecordCreateDialog title="Attach records" initialOpen={candidatesOpen} closeHref={`/reports/daily/${reportId}?linkedPage=${linkedPage}`}>{table(candidates.data, true)}<HistoryPagination path={`/reports/daily/${reportId}`} parameter="candidatePage" page={candidatePage} count={candidates.data[0]?.total_count ?? 0} filters={{ linkedPage: String(linkedPage) }} /></RecordCreateDialog></div><p className="mt-2 text-xs text-slate-500">Links to existing postings only. Attaching records does not change stock or project cost.</p>{table(linked.data, false)}<HistoryPagination path={`/reports/daily/${reportId}`} parameter="linkedPage" page={linkedPage} count={linked.data[0]?.total_count ?? 0} filters={{ candidatePage: String(candidatePage) }} /></section>;
}
