import Link from "next/link";
import { uuidSchema } from "@nognog/domain";
import { RecordCreateDialog } from "@/components/ui/record-create-dialog";
import { InventoryMovementForm } from "@/components/inventory/inventory-movement-form";
import { ReceiveTransferForm } from "@/components/inventory/transaction-action-form";
import { TransferVarianceForm } from "@/components/inventory/transfer-variance-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DataTableShell } from "@/components/ui/data-table-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { requireUser } from "@/lib/auth";
import { getInventoryOptions, getInventoryTransfers } from "@/lib/data/inventory";
export default async function TransfersPage({ searchParams }: { searchParams: Promise<{ new?: string; siteReturn?: string; receive?: string; variance?: string; material?: string }> }) { const params = await searchParams; const [user, transfers, options] = await Promise.all([requireUser(), getInventoryTransfers(), getInventoryOptions()]); const parsedMaterial = uuidSchema.safeParse(params.material); const receiving = user.canOperateInventory && params.receive ? transfers.find((item) => item.item?.id === params.receive && !item.requestBound && item.status !== "received" && item.status !== "cancelled") : undefined; const variance = !receiving && user.canManage && params.variance ? transfers.find((item) => item.item?.id === params.variance && !item.requestBound && item.status !== "received" && item.status !== "cancelled") : undefined; return <>
  <PageHeader eyebrow="Inventory movement" title="Transfers" description="Dispatch leaves the source immediately; destination stock updates only after receipt. Approved request deliveries are received on the request." action={<div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link href="/inventory">Back</Link></Button>{user.canManage && <Button variant="outline" asChild><Link href={params.siteReturn ? "/inventory/transfers" : "/inventory/transfers?siteReturn=1"}>{params.siteReturn ? "Close return" : "Return site stock"}</Link></Button>}{user.canOperateInventory && <Button asChild><Link href={params.new ? "/inventory/transfers" : "/inventory/transfers?new=1"}>{params.new ? "Close form" : "New transfer"}</Link></Button>}</div>} />
  {params.new && !params.siteReturn && !receiving && !variance && user.canOperateInventory && <RecordCreateDialog title="Transfer stock" initialOpen hideTrigger closeHref="/inventory/transfers"><InventoryMovementForm mode="transfer" initialMaterialId={parsedMaterial.success ? parsedMaterial.data : ""} {...options} /></RecordCreateDialog>}
  {params.siteReturn && !receiving && !variance && user.canManage && <RecordCreateDialog title="Return site stock" initialOpen hideTrigger closeHref="/inventory/transfers"><InventoryMovementForm mode="return" initialMaterialId={parsedMaterial.success ? parsedMaterial.data : ""} {...options} /></RecordCreateDialog>}
  {receiving?.item && <RecordCreateDialog title="Receive transfer" initialOpen hideTrigger closeHref="/inventory/transfers"><ReceiveTransferForm itemId={receiving.item.id} remaining={receiving.item.dispatched_quantity - receiving.item.received_quantity - receiving.item.variance_quantity} /></RecordCreateDialog>}
  {variance?.item && <RecordCreateDialog title="Review missing or damaged stock" initialOpen hideTrigger closeHref="/inventory/transfers"><TransferVarianceForm expanded itemId={variance.item.id} remaining={variance.item.dispatched_quantity - variance.item.received_quantity - variance.item.variance_quantity} unit={variance.material?.unitSymbol ?? ""} returnPath="/inventory/transfers" /></RecordCreateDialog>}
  <DataTableShell empty={transfers.length === 0 ? <EmptyState kind="items" title="No inventory transfers" description="Transfers will appear here after stock is dispatched between locations." /> : undefined}><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3">Transfer</th><th className="px-4 py-3">Material</th><th className="px-4 py-3">Route</th><th className="px-4 py-3 text-right">Dispatched</th><th className="px-4 py-3 text-right">In transit</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{transfers.map((item) => { const inTransit = item.status === "cancelled" ? 0 : (item.item?.dispatched_quantity ?? 0) - (item.item?.received_quantity ?? 0) - (item.item?.variance_quantity ?? 0); return <tr key={item.id}><td className="px-5 py-4"><p className="font-semibold">{item.transfer_number}</p><p className="text-xs text-slate-500">{item.external_reference}</p></td><td className="px-4 py-4">{item.material?.name ?? "Unavailable"}</td><td className="px-4 py-4 text-slate-600">{item.source?.name} → {item.destination?.name}</td><td className="px-4 py-4 text-right tabular-nums">{item.item?.dispatched_quantity ?? 0} {item.material?.unitSymbol}</td><td className="px-4 py-4 text-right font-semibold tabular-nums">{inTransit} {item.material?.unitSymbol}</td><td className="px-4 py-4"><Badge variant={item.status === "received" ? "active" : item.status === "cancelled" ? "neutral" : "review"}>{item.item?.variance_quantity ? item.status === "received" ? "Reconciled with variance" : "Partial · variance" : item.status.replace("_", " ")}</Badge></td><td className="px-5 py-4 text-right"><div className="flex justify-end gap-2">{item.requestBound ? <span className="text-xs text-slate-500">Material request</span> : user.canOperateInventory && inTransit > 0 && item.status !== "cancelled" ? <Button variant="ghost" size="sm" asChild><Link href={`/inventory/transfers?receive=${item.item?.id}`}>Receive</Link></Button> : null}{user.canManage && !item.requestBound && inTransit > 0 && <Button variant="ghost" size="sm" asChild><Link href={`/inventory/transfers?variance=${item.item?.id}`}>Variance</Link></Button>}</div></td></tr>; })}</tbody></table></DataTableShell>
  </>; }
