"use client";
import { useActionState, useState } from "react";
import { receiveTransferAction, reverseTransactionAction, type InventoryActionState } from "@/app/(workspace)/inventory/actions";
import { RecordFormControls } from "@/components/ui/record-create-dialog";
import { FormField, fieldControlClass } from "@/components/ui/form-field";
import { todayInManila } from "@/lib/date";
const initialState: InventoryActionState = { ok: false, message: "" };
export function ReceiveTransferForm({ itemId, remaining }: { itemId: string; remaining: number }) { const [state, action, pending] = useActionState(receiveTransferAction, initialState); const [key] = useState(() => globalThis.crypto.randomUUID()); return <form action={action} className="grid gap-4 border-b border-slate-200 bg-slate-50/60 p-5 md:grid-cols-[1fr_1fr_1.5fr_auto] md:items-end"><input type="hidden" name="idempotencyKey" value={key} /><input type="hidden" name="transferItemId" value={itemId} /><FormField label={`Quantity (max ${remaining})`} htmlFor="quantity" error={!state.ok ? state.fieldErrors?.quantity?.[0] : undefined}><input className={fieldControlClass} id="quantity" name="quantity" inputMode="decimal" required /></FormField><FormField label="Receipt date" htmlFor="transactionDate"><input className={fieldControlClass} id="transactionDate" name="transactionDate" type="date" defaultValue={todayInManila()} required /></FormField><FormField label="Remarks" htmlFor="remarks"><input className={fieldControlClass} id="remarks" name="remarks" /></FormField><RecordFormControls busy={pending} label="Confirm receipt" />{!state.ok && state.message && <p className="text-sm font-medium text-red-600 md:col-span-4">{state.message}</p>}</form>; }
export function ReversalForm({ transactionId }: { transactionId: string }) { const [state, action, pending] = useActionState(reverseTransactionAction, initialState); const [key] = useState(() => globalThis.crypto.randomUUID()); return <form action={action} className="grid gap-4 border-b border-red-100 bg-red-50/50 p-5 md:grid-cols-[1fr_auto] md:items-end"><input type="hidden" name="idempotencyKey" value={key} /><input type="hidden" name="transactionId" value={transactionId} /><FormField label="Reversal reason" htmlFor="reason" error={!state.ok ? state.fieldErrors?.reason?.[0] : undefined}><input className={fieldControlClass} id="reason" name="reason" minLength={3} required /></FormField><RecordFormControls busy={pending} label="Post reversal" />{!state.ok && state.message && <p className="text-sm font-medium text-red-600 md:col-span-2">{state.message}</p>}</form>; }
