import Link from "next/link";
import Image from "next/image";
import { PencilEdit02Icon, PlusSignIcon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { GenerateQrForm } from "@/components/qr/qr-action-form";
import { ProjectWorkforceSection } from "@/components/workforce/project-workforce-section";
import { requireUser } from "@/lib/auth";
import { getProject } from "@/lib/data/projects";
import { getProjectMaterialCost } from "@/lib/data/inventory";
import { getProjectWorkforce } from "@/lib/data/workforce";
import { getActiveQrCodesForEntities } from "@/lib/data/qr-codes";
import { recordPhotoUrl } from "@/lib/media/record-photo-url";
import { findMunicipality } from "@/lib/locations";
import { archiveProjectAction, assignProjectMemberAction, createProjectSiteAction, endProjectAssignmentAction } from "../actions";

const inputClass = "h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-cyan-600 focus:ring-4 focus:ring-cyan-600/10";
const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 2 });
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "Not recorded";

export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireUser();
  const [data, workforce] = await Promise.all([getProject(id), getProjectWorkforce(id, user.canViewLaborRates)]);
  const { project, assignments, sites, profiles } = data;
  const materialCosts = user.canManage || user.canViewLaborRates || user.roles.includes("project_manager") ? await getProjectMaterialCost(id) : null;
  const totalMaterialCost = materialCosts?.reduce((sum, row) => sum + Number(row.cost_total), 0) ?? 0;
  const municipality = project.municipality_code ? findMunicipality(project.municipality_code) : undefined;
  const siteQrCodes = user.canManage ? await getActiveQrCodesForEntities("project_site", sites.map((site) => site.id)) : [];
  const siteQrById = new Map(siteQrCodes.map((code) => [code.entity_id, code]));
  const profileName = (profileId: string | null) => profiles.find((profile) => profile.id === profileId)?.full_name ?? "Unassigned";
  return <>
    <div className="mb-5 flex flex-wrap gap-2">{user.canViewDailyReports && <Button variant="outline" asChild><Link href={`/projects/${id}/reports`}>View daily reports</Link></Button>}{user.canManage && <Button variant="outline" asChild><Link href={`/projects/${id}/attendance`}>Attendance & labor cost</Link></Button>}{user.canViewLaborRates && <Button variant="outline" asChild><Link href={`/projects/${id}/costs`}>Project costs & billing</Link></Button>}</div>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700">{project.code}</p><div className="mt-1.5 flex items-center gap-3"><h1 className="text-3xl font-semibold tracking-[-0.035em]">{project.name}</h1><Badge variant={project.status === "active" || project.status === "completed" ? "active" : project.status === "on_hold" ? "review" : "neutral"}>{project.status.replace("_", " ")}</Badge></div><p className="mt-1 text-sm text-slate-500">{project.client_name} · {project.city_province}</p></div>{user.canManage && <div className="flex gap-2"><Button variant="outline" asChild><Link href={`/projects/${id}/edit`}><HugeiconsIcon icon={PencilEdit02Icon} size={17} /> Edit</Link></Button><form action={archiveProjectAction}><input type="hidden" name="id" value={id} /><Button variant="outline" type="submit">Archive</Button></form></div>}</div>
    {project.photo_path && <div className="relative mt-6 h-52 overflow-hidden rounded-2xl bg-slate-100 sm:h-64"><Image src={recordPhotoUrl("projects", id)} alt={`${project.name} project`} fill sizes="(max-width: 768px) 100vw, 900px" unoptimized className="object-cover" /></div>}
    <section className="mt-8 grid gap-5 xl:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6 xl:col-span-2"><h2 className="font-semibold">Overview</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs text-slate-400">Address</dt><dd className="mt-1 text-sm font-medium">{project.address}</dd></div><div><dt className="text-xs text-slate-400">City / municipality</dt><dd className="mt-1 text-sm font-medium">{municipality ? `${municipality.displayName}, ${municipality.province} · ${municipality.region}${municipality.zipCode ? ` · ${municipality.zipCode}` : ""}` : project.city_province}</dd></div><div><dt className="text-xs text-slate-400">Project manager</dt><dd className="mt-1 text-sm font-medium">{profileName(project.project_manager_id)}</dd></div><div><dt className="text-xs text-slate-400">Start date</dt><dd className="mt-1 text-sm font-medium">{date(project.start_date)}</dd></div><div><dt className="text-xs text-slate-400">Target completion</dt><dd className="mt-1 text-sm font-medium">{date(project.target_completion_date)}</dd></div><div><dt className="text-xs text-slate-400">Actual completion</dt><dd className="mt-1 text-sm font-medium">{date(project.actual_completion_date)}</dd></div><div><dt className="text-xs text-slate-400">Estimated duration</dt><dd className="mt-1 text-sm font-medium">{project.estimated_duration_days} days</dd></div></dl>{project.description && <p className="mt-6 border-t border-slate-100 pt-5 text-sm leading-6 text-slate-600">{project.description}</p>}</article><article className="rounded-2xl border border-slate-200 bg-[#07152d] p-6 text-white"><h2 className="font-semibold">Budget record</h2><dl className="mt-6 space-y-5"><div><dt className="text-xs text-slate-400">Contract amount</dt><dd className="mt-1 text-xl font-semibold">{money.format(project.contract_amount)}</dd></div><div><dt className="text-xs text-slate-400">Initial budget</dt><dd className="mt-1 text-xl font-semibold">{money.format(project.initial_budget)}</dd></div></dl></article></section>
    {materialCosts && <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Actual material cost</h2><p className="mt-1 text-xs text-slate-500">Posted site consumption only; labor, equipment, and other expenses are not included.</p></div><p className="text-xl font-semibold tabular-nums">{money.format(totalMaterialCost)}</p></div>{materialCosts.length > 0 && <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b border-slate-100 text-xs text-slate-500"><tr><th className="py-3">SKU</th><th className="py-3">Material</th><th className="py-3 text-right">Used</th><th className="py-3 text-right">Cost</th></tr></thead><tbody className="divide-y divide-slate-100">{materialCosts.map((row) => <tr key={row.material_id}><td className="py-3 text-xs font-medium">{row.material_code}</td><td className="py-3">{row.material_name}</td><td className="py-3 text-right tabular-nums">{row.quantity} {row.unit_symbol}</td><td className="py-3 text-right font-medium tabular-nums">{money.format(Number(row.cost_total))}</td></tr>)}</tbody></table></div>}</section>}
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Personnel</h2><p className="mt-1 text-xs text-slate-500">Active and historical project assignments</p></div></div>{user.canManage && <form action={assignProjectMemberAction} className="mt-5 grid gap-3 border-b border-slate-100 pb-5 md:grid-cols-4"><input type="hidden" name="projectId" value={id} /><select className={inputClass} name="userId" required defaultValue=""><option value="" disabled>Select person</option>{profiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.full_name}</option>)}</select><select className={inputClass} name="role" defaultValue="worker"><option value="project_manager">Project manager</option><option value="engineer">Engineer</option><option value="foreman">Foreman</option><option value="worker">Worker</option></select><input className={inputClass} type="date" name="assignedOn" defaultValue={new Date().toISOString().slice(0, 10)} required /><Button type="submit"><HugeiconsIcon icon={PlusSignIcon} size={16} /> Assign</Button></form>}
      {assignments.length === 0 ? <EmptyState compact kind="items" title="No personnel assigned" /> : <div className="divide-y divide-slate-100">{assignments.map((assignment) => <div key={assignment.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{assignment.profile?.full_name ?? "Unavailable profile"}</p><p className="mt-0.5 text-xs capitalize text-slate-500">{assignment.assignment_role.replace("_", " ")} · Assigned {date(assignment.assigned_on)}</p></div><Badge variant={assignment.status === "active" ? "active" : "neutral"}>{assignment.status}</Badge>{user.canManage && assignment.status === "active" && <form action={endProjectAssignmentAction}><input type="hidden" name="assignmentId" value={assignment.id} /><input type="hidden" name="projectId" value={id} /><Button variant="ghost" size="sm" type="submit">End assignment</Button></form>}</div>)}</div>}
    </section>
    <ProjectWorkforceSection projectId={id} projectName={project.name} workforce={workforce} canManage={user.canManage} canViewRates={user.canViewLaborRates} />
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Project sites</h2><p className="mt-1 text-xs text-slate-500">Physical sites are inventory-ready locations.</p>{user.canManage && <form action={createProjectSiteAction} className="mt-5 grid gap-3 border-b border-slate-100 pb-5 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="projectId" value={id} /><input className={inputClass} name="name" placeholder="Site name" required /><input className={inputClass} name="address" placeholder="Site address" required /><input type="hidden" name="description" value="" /><select className={inputClass} name="engineerId" defaultValue=""><option value="">No engineer</option>{profiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.full_name}</option>)}</select><select className={inputClass} name="foremanId" defaultValue=""><option value="">No foreman</option>{profiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.full_name}</option>)}</select><input type="hidden" name="status" value="active" /><Button type="submit"><HugeiconsIcon icon={PlusSignIcon} size={16} /> Add site</Button></form>}
      {sites.length === 0 ? <EmptyState compact kind="items" title="No sites recorded" /> : <div className="mt-4 grid gap-4 md:grid-cols-2">{sites.map((site) => <article key={site.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><h3 className="text-sm font-semibold">{site.name}</h3><p className="mt-1 text-xs text-slate-500">{site.address}</p></div><Badge variant={site.status === "active" ? "active" : "neutral"}>{site.status}</Badge></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Engineer</dt><dd className="mt-1 font-medium">{profileName(site.engineer_id)}</dd></div><div><dt className="text-slate-400">Foreman</dt><dd className="mt-1 font-medium">{profileName(site.foreman_id)}</dd></div></dl>{user.canManage && <div className="mt-4 border-t border-slate-100 pt-4">{siteQrById.get(site.id) ? <Button asChild variant="outline" size="sm"><Link href={`/qr-codes/${siteQrById.get(site.id)!.id}`}>View QR label</Link></Button> : <GenerateQrForm entityType="project_site" entityId={site.id} />}</div>}</article>)}</div>}
    </section>
  </>;
}
