import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { RecordActionMenu } from "@/components/ui/record-action-menu";
import { recordPhotoUrl } from "@/lib/media/record-photo-url";
import type { SupplierListView } from "@/lib/data/suppliers";
import { SupplierPhoto } from "./supplier-photo";

export function SupplierCards({ suppliers, count, canManage }: { suppliers: SupplierListView[]; count: number; canManage: boolean }) {
  if (!suppliers.length) return <section className="mt-5 rounded-2xl border border-slate-200 bg-white"><EmptyState kind="results" title="No suppliers found" description="Adjust the filters or register the first supplier." /></section>;
  return <><section aria-label="Suppliers" className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{suppliers.map((supplier) => <article key={supplier.id} className="flex min-w-0 flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-start justify-between gap-3"><Link href={`/suppliers/${supplier.id}`} className="flex min-w-0 items-center gap-3 focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-600"><SupplierPhoto name={supplier.supplier_name} photo={supplier.photo_path ? recordPhotoUrl("suppliers", supplier.id) : undefined} className="size-14" sizes="56px" /><span className="min-w-0"><span className="block truncate text-base font-semibold text-slate-900 hover:text-cyan-700">{supplier.supplier_name}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{supplier.code} · {supplier.categoryName}</span></span></Link><Badge variant={supplier.archived_at ? "neutral" : supplier.status === "active" ? "active" : "review"}>{supplier.archived_at ? "archived" : supplier.status}</Badge></div><div className="mt-5 space-y-1 text-sm text-slate-600"><p className="truncate" title={supplier.business_name}>{supplier.business_name}</p><p className="truncate" title={`${supplier.city}, ${supplier.province}`}>{supplier.city}, {supplier.province}</p><p className="truncate" title={supplier.contact_number}>{supplier.contact_person} · {supplier.contact_number}</p><p className="truncate" title={supplier.email_address}>{supplier.email_address}</p></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Catalog materials</p><p className="mt-1 text-2xl font-semibold tabular-nums text-slate-900">{supplier.catalogCount}</p></div><div className="mt-auto flex justify-end pt-3"><RecordActionMenu name={supplier.supplier_name} actions={[{ label: "View", href: `/suppliers/${supplier.id}` }, ...(canManage && !supplier.archived_at ? [{ label: "Edit", href: `/suppliers/${supplier.id}/edit` }, { label: "Archive", href: `/suppliers/${supplier.id}#supplier-archive`, destructive: true }] : [])]} /></div></article>)}</section><p className="mt-3 text-sm text-slate-500">{count} supplier record{count === 1 ? "" : "s"}</p></>;
}
