import { ListFilterBar } from "@/components/ui/list-filter-bar";
import { IntentLink as Link } from "@/components/layout/intent-link";
import { z } from "zod";
import { uuidSchema } from "@nognog/domain";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { requireProcurementViewer } from "@/lib/auth";
import { getSupplierPriceComparison } from "@/lib/data/suppliers";
import type { MaterialAvailabilityStatus } from "@/types/database";

const availabilityOptions: Array<MaterialAvailabilityStatus | "all"> = ["all", "available", "limited", "unavailable", "discontinued"];
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "Present";
const money = (amount: number, currency: string) => new Intl.NumberFormat("en-PH", { style: "currency", currency, maximumFractionDigits: 2 }).format(amount);

export default async function SupplierPricesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireProcurementViewer(); const params = await searchParams;
  const parsedMaterial = uuidSchema.safeParse(params.material); const parsedSupplier = uuidSchema.safeParse(params.supplier);
  const materialId = parsedMaterial.success ? parsedMaterial.data : ""; const supplierId = parsedSupplier.success ? parsedSupplier.data : "";
  const availability = typeof params.availability === "string" && availabilityOptions.includes(params.availability as MaterialAvailabilityStatus | "all") ? params.availability as MaterialAvailabilityStatus | "all" : "all";
  const parsedDateFrom = z.iso.date().safeParse(params.from); const parsedDateTo = z.iso.date().safeParse(params.to);
  const dateFrom = parsedDateFrom.success ? parsedDateFrom.data : ""; const dateTo = parsedDateTo.success ? parsedDateTo.data : "";
  const data = await getSupplierPriceComparison({ materialId, supplierId, availability });
  const comparisonRows = data.rows.filter((row) => row.prices.current).sort((a, b) =>
    (a.material?.name ?? "").localeCompare(b.material?.name ?? "")
    || (a.unit?.code ?? "").localeCompare(b.unit?.code ?? "")
    || (a.prices.current?.currency ?? "").localeCompare(b.prices.current?.currency ?? "")
    || (a.prices.current?.unit_price ?? 0) - (b.prices.current?.unit_price ?? 0));
  const history = data.rows.flatMap((row) => row.prices.history.map((price) => ({ row, price }))).filter(({ price }) => (!dateFrom || price.effective_start_date >= dateFrom) && (!dateTo || price.effective_start_date <= dateTo)).sort((a, b) => b.price.effective_start_date.localeCompare(a.price.effective_start_date));
  return <><PageHeader eyebrow="Supplier intelligence" title="Material price comparison" description="Compare current supplier prices for the same material and unit." action={<Button variant="outline" asChild><Link href="/suppliers">Back to suppliers</Link></Button>} />
    <ListFilterBar className="mt-7 grid gap-3 border-y border-slate-200 bg-white p-4 lg:grid-cols-[1fr_1fr_180px_160px_160px_auto]"><select name="material" defaultValue={materialId} aria-label="Material" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All materials</option>{data.materials.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><select name="supplier" defaultValue={supplierId} aria-label="Supplier" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All suppliers</option>{data.suppliers.map((item) => <option key={item.id} value={item.id}>{item.supplier_name}</option>)}</select><select name="availability" defaultValue={availability} aria-label="Availability" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm">{availabilityOptions.map((item) => <option key={item} value={item}>{item === "all" ? "All availability" : item}</option>)}</select><input name="from" aria-label="Price effective from" type="date" defaultValue={dateFrom} className="h-10 rounded-lg border border-slate-200 px-3 text-sm" /><input name="to" aria-label="Price effective to" type="date" defaultValue={dateTo} className="h-10 rounded-lg border border-slate-200 px-3 text-sm" /></ListFilterBar>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Current comparable prices</h2><p className="mt-1 text-xs text-slate-500">Prices are compared only within the same unit and currency.</p></div>{!comparisonRows.length ? <EmptyState kind="results" title="No matching current prices" description="Change the filters to compare other suppliers or materials." /> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-5 py-3">Material</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Availability</th><th className="px-4 py-3">Lead time</th><th className="px-4 py-3 text-right">Previous</th><th className="px-4 py-3 text-right">Current</th><th className="px-5 py-3 text-right">Change</th></tr></thead><tbody className="divide-y divide-slate-100">{comparisonRows.map((row) => { const current = row.prices.current!; const previous = row.prices.previous; const difference = previous && previous.currency === current.currency ? current.unit_price - previous.unit_price : null; return <tr key={row.id}><td className="px-5 py-4"><p className="text-sm font-semibold">{row.material?.name ?? "Unavailable material"}</p><p className="text-xs text-slate-400">per {row.unit?.symbol ?? "unit"}</p></td><td className="px-4 py-4"><Link href={`/suppliers/${row.supplier_id}`} className="text-sm font-semibold hover:text-cyan-700">{row.supplier?.supplier_name ?? "Unavailable supplier"}</Link></td><td className="px-4 py-4"><Badge variant={row.availability_status === "available" ? "active" : row.availability_status === "limited" ? "review" : "neutral"}>{row.availability_status}</Badge></td><td className="px-4 py-4 text-sm text-slate-600">{row.lead_time_days === null ? "—" : `${row.lead_time_days} days`}</td><td className="px-4 py-4 text-right text-sm">{previous ? money(previous.unit_price, previous.currency) : "—"}</td><td className="px-4 py-4 text-right"><p className="text-sm font-semibold">{money(current.unit_price, current.currency)}</p><p className="text-xs text-slate-400">{date(current.effective_start_date)}</p></td><td className="px-5 py-4 text-right text-sm font-semibold">{difference === null ? "—" : `${difference > 0 ? "+" : ""}${money(difference, current.currency)}`}</td></tr>; })}</tbody></table></div>}</section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Price timeline</h2><p className="mt-1 text-xs text-slate-500">Price history for the selected supplier, material and dates.</p></div>{!history.length ? <EmptyState kind="results" title="No matching price history" description="Try a different supplier, material, or date range." /> : <div className="divide-y divide-slate-100">{history.map(({ row, price }) => <div key={price.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><p className="text-sm font-semibold">{row.material?.name ?? "Unavailable material"}</p><p className="text-xs text-slate-400">{row.unit?.name ?? "Unavailable unit"}</p></div><div><Link href={`/suppliers/${row.supplier_id}`} className="text-sm font-medium hover:text-cyan-700">{row.supplier?.supplier_name ?? "Unavailable supplier"}</Link><p className="text-xs text-slate-400">{date(price.effective_start_date)} – {date(price.effective_end_date)}</p></div><p className="text-right text-sm font-semibold">{money(price.unit_price, price.currency)}</p></div>)}</div>}</section>
  </>;
}
