export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Table<Row, Insert, Update = Partial<Insert>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type AppRole = "admin" | "engineer" | "foreman" | "warehouse_staff" | "finance";
export type ProjectStatus = "draft" | "active" | "on_hold" | "completed" | "cancelled";
export type ProjectDocumentCategory = "initial" | "other";
export type AssignmentRole = "engineer" | "foreman";
export type AssignmentStatus = "active" | "inactive";
export type WarehouseStatus = "active" | "inactive";
export type MaterialKind = "consumable" | "reusable";
export type InventoryTransactionType = "OPENING_BALANCE" | "STOCK_IN" | "STOCK_OUT" | "WAREHOUSE_TRANSFER" | "SITE_TRANSFER" | "MATERIAL_CONSUMPTION" | "MATERIAL_RETURN" | "INVENTORY_ADJUSTMENT" | "REVERSAL";
export type MaterialRequestStatus = "submitted" | "approved" | "partially_approved" | "rejected" | "cancelled";
export type MaterialRequestRow = { id: string; request_number: string; submission_key: string; submission_hash: string; project_id: string; project_site_id: string; source_warehouse_id: string; source_warehouse_name: string; required_date: string; purpose: string; status: MaterialRequestStatus; requested_by: string; requested_at: string; decided_by: string | null; decided_at: string | null; decision_reason: string | null };
export type MaterialSourcingRequestRow = { id: string; idempotency_key: string; payload_hash: string; project_id: string; project_site_id: string; source_warehouse_id: string; project_name: string; site_name: string; warehouse_name: string; material_name: string; unit_name: string; requested_quantity: number; needed_on: string; reason: string; status: "submitted" | "resolved" | "dismissed"; catalog_material_id: string | null; resolution_note: string | null; requested_by: string; resolved_by: string | null; resolved_at: string | null; created_at: string };
export type MaterialRequestLineRow = { id: string; request_id: string; material_id: string; unit_of_measure_id: string; requested_quantity: number; approved_quantity: number };
export type MaterialRequestReservationRow = { id: string; request_line_id: string; material_id: string; inventory_location_id: string; original_quantity: number; remaining_quantity: number; status: "active" | "fulfilled" | "released"; reserved_by: string; reserved_at: string; released_at: string | null };
export type MaterialRequestReservationEventRow = { id: string; reservation_id: string; event_type: "reserved" | "dispatched" | "released"; quantity: number; actor_id: string; occurred_at: string };
export type MaterialRequestEventRow = { id: string; request_id: string; event_type: MaterialRequestStatus; actor_id: string; details: Json; occurred_at: string };
export type MaterialRequestDispatchRow = { id: string; request_line_id: string; transfer_item_id: string; created_at: string };
export type MaterialDeliveryManifestRow = { transfer_id: string; vehicle_asset_id: string | null; vehicle_label: string; driver_name: string; delivery_reference: string; payload_hash: string; dispatched_by: string; created_at: string };
export type MaterialDeliveryAcceptanceRow = { inventory_transaction_id: string; transfer_item_id: string; received_quantity: number; condition: "accepted" | "accepted_with_note"; quality_note: string | null; inspection_payload_hash: string | null; received_by: string; created_at: string };
export type MaterialRequestFulfillmentEventRow = { id: string; request_line_id: string; transfer_item_id: string; event_type: "dispatched" | "received"; quantity: number; actor_id: string; occurred_at: string };
export type ApprovedRequestQueueRow = { request_line_id: string; request_id: string; request_number: string; project_code: string; project_name: string; site_name: string; warehouse_id: string; warehouse_name: string; material_code: string; material_name: string; approved_quantity: number; dispatched_quantity: number; available_quantity: number; reserved_quantity: number; unit_symbol: string; total_count: number };
export type AssetKind = "equipment" | "vehicle";
export type AssetOwnershipType = "company_owned" | "rented" | "leased";
export type AssetStatus = "available" | "assigned" | "in_use" | "under_maintenance" | "out_of_service" | "retired";
export type AssetLocationKind = "warehouse" | "project_site" | "maintenance_facility" | "other";
export type AssetEventType = "registered" | "details_updated" | "status_changed" | "location_changed" | "archived";
export type EmployeeStatus = "active" | "inactive" | "on_leave" | "separated";
export type WorkforceAssignmentStatus = "active" | "ended";
export type LaborRateType = "hourly" | "daily";
export type EmployeeEventType = "registered" | "details_updated" | "status_changed" | "profile_linked" | "archived" | "assignment_started" | "assignment_ended" | "assignment_transferred" | "rate_added" | "rate_closed";
export type SupplierStatus = "active" | "inactive";
export type MaterialAvailabilityStatus = "available" | "limited" | "unavailable" | "discontinued";
export type SupplierEventType = "registered" | "details_updated" | "status_changed" | "archived" | "material_added" | "material_updated" | "material_archived" | "price_added" | "price_closed";
export type DailyReportStatus = "draft" | "submitted" | "pending_review" | "approved" | "rejected" | "requires_revision";
export type DailyReportEventType = "created" | "draft_updated" | "submitted" | "approved" | "returned_for_correction" | "revision_started";
export type QrEntityType = "material" | "equipment" | "vehicle" | "warehouse" | "project_site";
export type QrStatus = "active" | "inactive" | "replaced";
export type QrCodeRow = { id: string; public_identifier: string; entity_type: QrEntityType; entity_id: string; material_id: string | null; asset_id: string | null; warehouse_id: string | null; project_site_id: string | null; status: QrStatus; generated_by: string; generated_at: string; activated_at: string; deactivated_at: string | null; replaces_qr_id: string | null; remarks: string | null };
export type QrEventRow = { id: string; qr_code_id: string; event_type: "generated" | "deactivated" | "replaced"; actor_id: string; remarks: string | null; occurred_at: string };
export type QrResolution = { qr_id: string; identifier: string; entity_type: QrEntityType; entity_id: string; name: string; code: string | null; project_id: string | null };
export type NotificationTypeCode = import("@nognog/domain").NotificationTypeCode;
export type NotificationPriority = import("@nognog/domain").NotificationPriority;
export type NotificationOutboxStatus = "pending" | "retry" | "delivered" | "failed";
export type NotificationTypeRow = { code: NotificationTypeCode; label: string; is_enabled: boolean; is_sensitive: boolean };
export type NotificationOutboxRow = { id: string; event_key: string; type_code: NotificationTypeCode; title: string; message: string; entity_type: string; entity_id: string | null; project_id: string | null; warehouse_id: string | null; priority: NotificationPriority; recipient_roles: AppRole[]; recipient_user_ids: string[]; expires_at: string | null; status: NotificationOutboxStatus; attempts: number; next_attempt_at: string; last_error: string | null; created_at: string; processed_at: string | null };
export type NotificationRow = { id: string; event_id: string; recipient_id: string; type_code: NotificationTypeCode; title: string; message: string; entity_type: string; entity_id: string | null; project_id: string | null; warehouse_id: string | null; priority: NotificationPriority; read_at: string | null; created_at: string; expires_at: string | null };
export type NotificationReadEventRow = { id: string; notification_id: string; recipient_id: string; read_at: string };

export type ProfileRow = { id: string; full_name: string; email: string; phone: string | null; avatar_path: string | null; is_active: boolean; onboarding_required: boolean; created_at: string; updated_at: string };
export type ProjectRow = {
  id: string; code: string; name: string; photo_path: string | null; description: string | null; client_name: string; client_email: string | null; client_phone: string | null;
  address: string; city_province: string; municipality_code: string | null; start_date: string; target_completion_date: string; actual_completion_date: string | null;
  estimated_duration_days: number; contract_amount: number; initial_budget: number; status: ProjectStatus; project_manager_id: string | null;
  created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string;
};
export type ProjectDocumentRow = { id: string; project_id: string; category: ProjectDocumentCategory; file_name: string; content_type: string; file_size: number; storage_path: string; uploaded_by: string; created_at: string };
export type WarehouseRow = {
  id: string; code: string; name: string; photo_path: string | null; description: string | null; address: string; municipality_code: string | null; contact_person: string | null; contact_number: string | null;
  status: WarehouseStatus; created_by: string; updated_by: string; created_at: string; updated_at: string;
};
export type ProjectAssignmentRow = { id: string; project_id: string; user_id: string; assignment_role: AssignmentRole; status: AssignmentStatus; assigned_on: string; assigned_by: string; ended_at: string | null; ended_by: string | null; created_at: string; updated_at: string };
export type WarehouseAssignmentRow = { id: string; warehouse_id: string; user_id: string; status: AssignmentStatus; assigned_on: string; assigned_by: string; ended_at: string | null; ended_by: string | null; created_at: string; updated_at: string };
export type ProjectSiteRow = { id: string; project_id: string; name: string; address: string; description: string | null; engineer_id: string | null; foreman_id: string | null; status: "active" | "inactive"; created_by: string; updated_by: string; created_at: string; updated_at: string };
export type UnitRow = { id: string; code: string; name: string; symbol: string; dimension: "count" | "mass" | "volume" | "length" | "area"; decimal_scale: number; is_active: boolean; created_at: string };
export type MaterialCategoryRow = { id: string; name: string; description: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type MaterialRow = { id: string; code: string; name: string; description: string | null; photo_path: string | null; category_id: string; base_unit_id: string; material_kind: MaterialKind; minimum_stock_level: number; is_active: boolean; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type InventoryLocationRow = { id: string; location_type: "warehouse" | "project_site"; warehouse_id: string | null; project_site_id: string | null; created_at: string };
export type InventoryBalanceRow = { id: string; material_id: string; inventory_location_id: string; quantity_on_hand: number; reserved_quantity: number; available_quantity: number; updated_at: string };
export type InventoryLowStockAlertRow = { id: string; inventory_balance_id: string; material_id: string; inventory_location_id: string; threshold_quantity: number; available_at_open: number; opened_at: string; resolved_at: string | null };
export type InventoryTransferRow = { id: string; transfer_number: string; source_location_id: string; destination_location_id: string; external_reference: string; status: "dispatched" | "partially_received" | "received" | "cancelled"; dispatched_by: string; dispatched_at: string; received_by: string | null; received_at: string | null; remarks: string | null; created_at: string; updated_at: string };
export type InventoryTransferItemRow = { id: string; transfer_id: string; material_id: string; unit_of_measure_id: string; dispatched_quantity: number; received_quantity: number; variance_quantity: number; dispatched_total_cost: number | null; received_total_cost: number; variance_total_cost: number; created_at: string; updated_at: string };
export type InventoryTransferVarianceRow = { id: string; transfer_item_id: string; quantity: number; cost_total: number; reason: string; approved_by: string; approved_at: string };
export type InventoryTransactionRow = { id: string; material_id: string; quantity: number; unit_of_measure_id: string; source_location_id: string | null; destination_location_id: string | null; transaction_type: InventoryTransactionType; transfer_id: string | null; transfer_item_id: string | null; transfer_phase: "dispatch" | "receipt" | null; reference_document: string; project_id: string | null; responsible_user_id: string; transaction_date: string; remarks: string | null; reversal_of: string | null; cost_total: number | null; cost_unit: number | null; created_at: string };
export type InventoryValuationRow = { id: string; material_id: string; inventory_location_id: string; quantity_on_hand: number; total_value: number | null; updated_at: string };
export type InventoryOpeningValueRow = { id: string; material_id: string; inventory_location_id: string; verified_quantity: number; verified_total_value: number; reason: string; verified_by: string; verified_at: string };
export type AssetCategoryRow = { id: string; asset_kind: AssetKind; name: string; description: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type AssetLocationRow = { id: string; location_kind: AssetLocationKind; inventory_location_id: string | null; name: string | null; address: string | null; created_by: string | null; updated_by: string | null; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type AssetRow = { photo_path: string | null; id: string; asset_kind: AssetKind; code: string; name: string; description: string | null; category_id: string; brand: string; model: string; acquisition_date: string; ownership_type: AssetOwnershipType; status: AssetStatus; current_location_id: string; condition_notes: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type EquipmentDetailRow = { asset_id: string; equipment_type: string; serial_number: string; acquisition_cost: number; sku: string | null };
export type VehicleDetailRow = { asset_id: string; plate_number: string; manufacture_year: number; current_mileage: number };
export type AssetEventRow = { id: string; asset_id: string; event_type: AssetEventType; previous_status: AssetStatus | null; current_status: AssetStatus | null; previous_location_id: string | null; current_location_id: string | null; summary: string; details: Json; actor_id: string; occurred_at: string };
export type EquipmentRequestStatus = "submitted" | "approved" | "rejected" | "checked_out" | "returned";
export type EquipmentRequestRow = { id: string; asset_id: string; asset_code: string; asset_name: string; project_id: string; project_site_id: string; requested_by: string; needed_on: string; expected_return_on: string; purpose: string; status: EquipmentRequestStatus; decided_by: string | null; decided_at: string | null; decision_note: string | null; source_location_id: string | null; checked_out_by: string | null; checked_out_at: string | null; returned_by: string | null; returned_at: string | null; return_note: string | null; created_at: string; updated_at: string };
export type EmployeeCategoryRow = { id: string; name: string; description: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type EmployeeRow = { id: string; code: string; first_name: string; middle_name: string | null; last_name: string; category_id: string; employment_type: string; status: EmployeeStatus; hire_date: string; profile_id: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type EmployeePrivateContactRow = { employee_id: string; contact_number: string; email_address: string | null; updated_by: string; updated_at: string };
export type EmployeeProjectAssignmentRow = { id: string; employee_id: string; project_id: string; project_site_id: string; position_title: string; start_date: string; end_date: string | null; status: WorkforceAssignmentStatus; assigned_by: string; ended_by: string | null; remarks: string | null; end_remarks: string | null; transferred_from_assignment_id: string | null; created_at: string; updated_at: string };
export type LaborRateRow = { id: string; employee_id: string; rate_type: LaborRateType; rate_amount: number; effective_start_date: string; effective_end_date: string | null; approved_by: string; created_at: string; updated_at: string };
export type EmployeeEventRow = { id: string; employee_id: string; event_type: EmployeeEventType; previous_status: EmployeeStatus | null; current_status: EmployeeStatus | null; summary: string; details: Json; actor_id: string; occurred_at: string };
export type SupplierCategoryRow = { id: string; name: string; description: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type SupplierRow = { id: string; code: string; supplier_name: string; business_name: string; photo_path: string | null; category_id: string; contact_person: string; contact_number: string; email_address: string; business_address: string; city: string; province: string; tax_identification_number: string | null; payment_terms: string; status: SupplierStatus; remarks: string | null; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type SupplierMaterialRow = { id: string; supplier_id: string; material_id: string; supplier_material_code: string; unit_of_measure_id: string; minimum_order_quantity: number; lead_time_days: number | null; availability_status: MaterialAvailabilityStatus; created_by: string; updated_by: string; archived_at: string | null; archived_by: string | null; created_at: string; updated_at: string };
export type SupplierPriceRow = { id: string; supplier_material_id: string; unit_price: number; effective_start_date: string; effective_end_date: string | null; currency: string; recorded_by: string; created_at: string; updated_at: string };
export type SupplierEventRow = { id: string; supplier_id: string; event_type: SupplierEventType; summary: string; details: Json; actor_id: string; occurred_at: string };
export type ClientInvoiceRow = { id: string; invoice_number: string; project_id: string; project_code: string; project_name: string; client_name: string; description: string; issued_on: string; due_on: string; amount: number; status: "issued" | "void"; issued_by: string; voided_by: string | null; voided_at: string | null; void_reason: string | null; idempotency_key: string; command_payload: Json; created_at: string };
export type ClientPaymentRow = { id: string; invoice_id: string; amount: number; paid_on: string; reference: string; recorded_by: string; idempotency_key: string; command_payload: Json; created_at: string };
export type ClientPaymentReversalRow = { id: string; payment_id: string; reason: string; reversed_by: string; reversed_at: string; idempotency_key: string; command_payload: Json };
export type ClientInvoiceBalanceRow = { invoice_id: string; paid_amount: number; outstanding_amount: number };
export type PurchaseOrderRow = { id: string; po_number: string; supplier_id: string; supplier_name: string; warehouse_id: string; warehouse_code: string; warehouse_name: string; ordered_on: string; expected_on: string; purpose: string; status: "issued" | "partially_received" | "received" | "cancelled"; issued_by: string; cancelled_by: string | null; cancelled_at: string | null; cancellation_reason: string | null; idempotency_key: string; command_payload: Json; created_at: string; updated_at: string };
export type PurchaseOrderLineRow = { id: string; purchase_order_id: string; supplier_material_id: string; material_id: string; material_code: string; material_name: string; unit_of_measure_id: string; unit_symbol: string; ordered_quantity: number; received_quantity: number; unit_price: number; supplier_price_id: string; created_at: string };
export type PurchaseOrderReceiptRow = { id: string; purchase_order_id: string; purchase_order_line_id: string; inventory_transaction_id: string; quantity: number; goods_total_cost: number; expected_total_cost: number; cost_variance_reason: string | null; delivery_reference: string; received_on: string; received_by: string; idempotency_key: string; command_payload: Json; created_at: string };
export type ProjectAttendanceRow = { id: string; employee_id: string; assignment_id: string; project_id: string; project_site_id: string; work_date: string; attendance_status: "present" | "absent"; hours_worked: number; billable_units: number; rate_id: string | null; rate_type: LaborRateType | null; rate_snapshot: number | null; cost_total: number; note: string; recorded_by: string; idempotency_key: string; command_payload: Json; created_at: string };
export type ProjectAttendanceReversalRow = { id: string; attendance_id: string; reason: string; reversed_by: string; reversed_at: string; idempotency_key: string; command_payload: Json };
export type EquipmentHourRateRow = { id: string; asset_id: string; hourly_rate: number; effective_start_date: string; effective_end_date: string | null; approved_by: string; created_at: string };
export type ProjectEquipmentUsageRow = { id: string; project_id: string; asset_id: string; asset_code: string; asset_name: string; use_date: string; hours_used: number; rate_id: string; hourly_rate_snapshot: number; cost_total: number; work_note: string; start_photo_path: string | null; end_photo_path: string | null; recorded_by: string; idempotency_key: string; command_payload: Json; created_at: string };
export type ProjectEquipmentUsageReversalRow = { id: string; usage_id: string; reason: string; reversed_by: string; reversed_at: string; idempotency_key: string; command_payload: Json };
export type ProjectAdditionalExpenseRow = { id: string; project_id: string; expense_date: string; category: "permit" | "subcontract" | "utilities" | "other"; description: string; external_reference: string; amount: number; recorded_by: string; idempotency_key: string; command_payload: Json; created_at: string };
export type ProjectExpenseReversalRow = { id: string; expense_id: string; reason: string; reversed_by: string; reversed_at: string; idempotency_key: string; command_payload: Json };
export type ProjectBudgetChangeRow = { id: string; project_id: string; change_amount: number; reason: string; approved_by: string; approved_at: string; idempotency_key: string; command_payload: Json };
export type ProjectManagementSummaryRow = { project_code: string; project_name: string; contract_amount: number; approved_budget: number; material_cost: number; labor_cost: number; equipment_cost: number; additional_cost: number; total_cost: number; invoiced_amount: number; cash_received: number; billed_margin: number };
export type ProjectProfitabilityRow = { project_code: string; project_name: string; contract_value: number; approved_budget: number; material_cost: number; labor_cost: number; equipment_cost: number; other_cost: number; site_stock_loss_cost: number; transfer_loss_cost: number; total_posted_cost: number; estimated_gross_profit: number; estimated_gross_margin_percent: number | null; invoiced_amount: number; cash_received: number; receivables: number };
export type DashboardMonthlyCostRow = { month_start: string; material_cost: number; labor_cost: number; equipment_cost: number; other_cost: number };
export type ProjectMaterialPlanRow = { id: string; project_id: string; project_site_id: string; warehouse_id: string; material_id: string; planned_quantity: number; required_on: string; note: string; updated_by: string; created_at: string; updated_at: string };
export type ProjectMaterialPlanView = { id: string; project_site_id: string; site_name: string; warehouse_id: string; warehouse_name: string; material_id: string; material_code: string; material_name: string; unit_symbol: string; planned_quantity: number; required_on: string; note: string; consumed_quantity: number; site_on_hand: number; warehouse_available: number; outstanding_request_quantity: number; quantity_to_request: number; procurement_shortage: number };
export type ProjectMaterialEstimateView = { plan_line_id: string; unit_cost: number | null; price_source: "supplier" | "stock" | null; estimated_cost: number | null };
export type ProjectProgressRow = { id: string; project_id: string; project_site_id: string; daily_report_id: string; progress_date: string; completion_percent: number; summary: string; recorded_by: string; recorded_at: string };
export type InventoryStockCountRow = { id: string; idempotency_key: string; material_id: string; inventory_location_id: string; expected_quantity: number; expected_reserved: number; expected_value: number; counted_quantity: number; reason_type: "physical_count" | "damaged" | "missing"; reason: string; status: "pending" | "approved" | "rejected"; counted_by: string; counted_at: string; decided_by: string | null; decided_at: string | null; decision_note: string | null; transaction_id: string | null };
export type LegacyTransitValueRow = { id: string; transfer_item_id: string; verified_dispatched_total_cost: number; verified_received_total_cost: number; supporting_reference: string; reason: string; verified_by: string; verified_at: string; idempotency_key: string; command_payload: Json };
export type LegacyTransitQueueRow = { transfer_item_id: string; transfer_number: string; material_code: string; material_name: string; source_name: string; destination_name: string; dispatched_quantity: number; received_quantity: number; remaining_quantity: number };
export type DailyReportRow = { id: string; report_number: string; project_id: string; project_site_id: string; report_date: string; prepared_by: string; status: DailyReportStatus; weather_conditions: string | null; work_description: string; accomplishments: string; issues_encountered: string | null; site_observations: string | null; general_remarks: string | null; photo_path: string | null; revision: number; created_at: string; updated_at: string; submitted_at: string | null; approved_at: string | null; approved_by: string | null };
export type DailyReportEventRow = { id: string; report_id: string; revision: number; event_type: DailyReportEventType; actor_id: string; report_snapshot: Json; occurred_at: string };

export type Database = {
  public: {
    Tables: {
      profiles: Table<ProfileRow, { id: string; full_name: string; email: string; phone?: string | null; avatar_path?: string | null; is_active?: boolean; onboarding_required?: boolean }>;
      user_roles: Table<{ user_id: string; role: AppRole; granted_by: string | null; granted_at: string }, { user_id: string; role: AppRole; granted_by?: string | null }>;
      geo_regions: Table<{ code: string; name: string }, never>;
      geo_provinces: Table<{ code: string; name: string; region_code: string }, never>;
      geo_municipalities: Table<{ code: string; name: string; display_name: string; province_code: string | null; region_code: string; province_name: string; region_name: string; kind: string; selectable: boolean; zip_code: string; district: string }, never>;
      geo_barangays: Table<{ code: string; name: string; municipality_code: string }, never>;
      projects: Table<ProjectRow, Omit<ProjectRow, "id" | "photo_path" | "municipality_code" | "estimated_duration_days" | "archived_at" | "archived_by" | "created_at" | "updated_at"> & { id?: string; photo_path?: string | null; municipality_code?: string | null; archived_at?: string | null; archived_by?: string | null }>;
      project_assignments: Table<ProjectAssignmentRow, Omit<ProjectAssignmentRow, "id" | "status" | "ended_at" | "ended_by" | "created_at" | "updated_at"> & { id?: string; status?: AssignmentStatus }, Partial<ProjectAssignmentRow>>;
      project_documents: Table<ProjectDocumentRow, Omit<ProjectDocumentRow, "created_at">, never>;
      warehouses: Table<WarehouseRow, Omit<WarehouseRow, "id" | "photo_path" | "municipality_code" | "created_at" | "updated_at"> & { id?: string; photo_path?: string | null; municipality_code?: string | null }>;
      warehouse_assignments: Table<WarehouseAssignmentRow, Omit<WarehouseAssignmentRow, "id" | "status" | "ended_at" | "ended_by" | "created_at" | "updated_at"> & { id?: string; status?: AssignmentStatus }, Partial<WarehouseAssignmentRow>>;
      project_sites: Table<ProjectSiteRow, Omit<ProjectSiteRow, "id" | "created_at" | "updated_at"> & { id?: string }>;
      project_warehouses: Table<{ project_id: string; warehouse_id: string; authorized_by: string; authorized_at: string }, { project_id: string; warehouse_id: string; authorized_by: string }>;
      inventory_locations: Table<InventoryLocationRow, never>;
      units_of_measure: Table<UnitRow, never>;
      material_categories: Table<MaterialCategoryRow, never>;
      materials: Table<MaterialRow, never>;
      inventory_balances: Table<InventoryBalanceRow, never>;
      inventory_stock_counts: Table<InventoryStockCountRow, never>;
      inventory_low_stock_alerts: Table<InventoryLowStockAlertRow, never>;
      inventory_transfers: Table<InventoryTransferRow, never>;
      inventory_transfer_items: Table<InventoryTransferItemRow, never>;
      inventory_transfer_variances: Table<InventoryTransferVarianceRow, never>;
      inventory_transactions: Table<InventoryTransactionRow, never>;
      inventory_valuations: Table<InventoryValuationRow, never>;
      inventory_opening_values: Table<InventoryOpeningValueRow, never>;
      valuation_command_receipts: Table<{ idempotency_key: string; actor_id: string; command_name: string; payload_hash: string; result_id: string; created_at: string }, never>;
      inventory_command_receipts: Table<{ idempotency_key: string; actor_id: string; command_name: string; result_id: string; created_at: string }, never>;
      material_requests: Table<MaterialRequestRow, never>;
      material_sourcing_requests: Table<MaterialSourcingRequestRow, never>;
      material_request_lines: Table<MaterialRequestLineRow, never>;
      material_request_reservations: Table<MaterialRequestReservationRow, never>;
      material_request_reservation_events: Table<MaterialRequestReservationEventRow, never>;
      material_request_events: Table<MaterialRequestEventRow, never>;
      material_request_dispatches: Table<MaterialRequestDispatchRow, never>;
      material_delivery_manifests: Table<MaterialDeliveryManifestRow, never>;
      material_delivery_acceptances: Table<MaterialDeliveryAcceptanceRow, never>;
      material_request_fulfillment_events: Table<MaterialRequestFulfillmentEventRow, never>;
      material_request_decision_receipts: Table<{ idempotency_key: string; request_id: string; actor_id: string; payload_hash: string; created_at: string }, never>;
      material_request_cancellation_receipts: Table<{ idempotency_key: string; request_id: string; actor_id: string; payload_hash: string; created_at: string }, never>;
      asset_categories: Table<AssetCategoryRow, never>;
      asset_locations: Table<AssetLocationRow, never>;
      assets: Table<AssetRow, never>;
      equipment_details: Table<EquipmentDetailRow, never>;
      vehicle_details: Table<VehicleDetailRow, never>;
      asset_events: Table<AssetEventRow, never>;
      equipment_requests: Table<EquipmentRequestRow, never>;
      employee_categories: Table<EmployeeCategoryRow, never>;
      employees: Table<EmployeeRow, never>;
      employee_private_contacts: Table<EmployeePrivateContactRow, never>;
      employee_project_assignments: Table<EmployeeProjectAssignmentRow, never>;
      labor_rates: Table<LaborRateRow, never>;
      employee_events: Table<EmployeeEventRow, never>;
      supplier_categories: Table<SupplierCategoryRow, never>;
      suppliers: Table<SupplierRow, never>;
      supplier_materials: Table<SupplierMaterialRow, never>;
      supplier_prices: Table<SupplierPriceRow, never>;
      supplier_events: Table<SupplierEventRow, never>;
      client_invoices: Table<ClientInvoiceRow, never>;
      client_payments: Table<ClientPaymentRow, never>;
      client_payment_reversals: Table<ClientPaymentReversalRow, never>;
      purchase_orders: Table<PurchaseOrderRow, never>;
      purchase_order_lines: Table<PurchaseOrderLineRow, never>;
      purchase_order_receipts: Table<PurchaseOrderReceiptRow, never>;
      project_attendance: Table<ProjectAttendanceRow, never>;
      project_attendance_reversals: Table<ProjectAttendanceReversalRow, never>;
      equipment_hour_rates: Table<EquipmentHourRateRow, never>;
      project_equipment_usage: Table<ProjectEquipmentUsageRow, never>;
      project_equipment_usage_reversals: Table<ProjectEquipmentUsageReversalRow, never>;
      project_additional_expenses: Table<ProjectAdditionalExpenseRow, never>;
      project_expense_reversals: Table<ProjectExpenseReversalRow, never>;
      project_budget_changes: Table<ProjectBudgetChangeRow, never>;
      project_material_plan_lines: Table<ProjectMaterialPlanRow, never>;
      project_progress_entries: Table<ProjectProgressRow, never>;
      inventory_legacy_transit_values: Table<LegacyTransitValueRow, never>;
      daily_reports: Table<DailyReportRow, never>;
      daily_report_events: Table<DailyReportEventRow, never>;
      qr_codes: Table<QrCodeRow, never>;
      qr_events: Table<QrEventRow, never>;
      notification_types: Table<NotificationTypeRow, never>;
      notification_outbox: Table<NotificationOutboxRow, never>;
      notifications: Table<NotificationRow, never>;
      notification_read_events: Table<NotificationReadEventRow, never>;
      audit_logs: Table<{ id: number; actor_id: string | null; table_name: string; record_id: string | null; action: string; old_data: Json | null; new_data: Json | null; created_at: string }, never>;
    };
    Views: Record<string, never>;
    Functions: {
      get_mobile_projects: { Args: { p_search?: string; p_id?: string | null; p_offset?: number; p_limit?: number }; Returns: { record: Json; total_count: number }[] };
      mark_mobile_notification_unread: { Args: { p_id: string }; Returns: boolean };
      submit_equipment_request_once: { Args: { p_key: string; p_asset_id: string; p_project_id: string; p_site_id: string; p_needed_on: string; p_expected_return_on: string; p_purpose: string }; Returns: string };
      post_project_attendance_batch: { Args: { p_project_id: string; p_site_id: string; p_work_date: string; p_entries: Json }; Returns: string[] };
      get_mobile_site_operations: { Args: { p_kind: string; p_project_id: string; p_site_id: string; p_date?: string; p_search?: string; p_offset?: number; p_limit?: number }; Returns: { record: Json; total_count: number }[] };
      guard_mobile_api: { Args: { p_write: boolean }; Returns: boolean };
      search_site_material_choices: { Args: { p_location_id: string; p_search?: string; p_offset?: number; p_limit?: number }; Returns: { id: string; label: string; unit_id: string; available_quantity: number; total_count: number }[] };
      search_requestable_warehouse_stock: { Args: { p_project_id: string; p_warehouse_id: string; p_search?: string; p_offset?: number; p_limit?: number; p_material_id?: string | null }; Returns: { id: string; label: string; unit_id: string; available_quantity: number; total_count: number }[] };
      submit_material_sourcing_request: { Args: { p_key: string; p_project_id: string; p_site_id: string; p_warehouse_id: string; p_material_name: string; p_unit_name: string; p_quantity: number | string; p_needed_on: string; p_reason: string }; Returns: string };
      resolve_material_sourcing_request: { Args: { p_id: string; p_action: "resolved" | "dismissed"; p_material_id: string | null; p_note: string }; Returns: string };
      get_delivery_vehicle_choices: { Args: Record<string, never>; Returns: { id: string; label: string }[] };
      dispatch_approved_request_line_with_manifest: { Args: { p_idempotency_key: string; p_request_line_id: string; p_quantity: number | string; p_transaction_date: string; p_remarks: string | null; p_vehicle_asset_id: string | null; p_vehicle_label: string; p_driver_name: string; p_delivery_reference: string }; Returns: string };
      receive_request_transfer_with_inspection: { Args: { p_idempotency_key: string; p_transfer_item_id: string; p_quantity: number | string; p_transaction_date: string; p_remarks: string | null; p_condition: "accepted" | "accepted_with_note"; p_quality_note: string | null }; Returns: string };
      search_material_choices: { Args: { p_search?: string; p_offset?: number; p_limit?: number }; Returns: { id: string; label: string; unit_id: string; total_count: number }[] };
      search_attendance_assignment_choices: { Args: { p_project_id: string; p_search?: string; p_offset?: number; p_limit?: number }; Returns: { id: string; label: string; unit_id: string | null; total_count: number }[] };
      list_supplier_price_history: { Args: { p_supplier_id: string; p_offset?: number; p_limit?: number }; Returns: { record: Json; total_count: number }[] };
      list_supplier_summary_prices: { Args: { p_supplier_id: string; p_as_of: string }; Returns: SupplierPriceRow[] };
      attach_daily_report_resource: { Args: { p_report_id: string; p_kind: string; p_resource_id: string }; Returns: undefined };
      detach_daily_report_resource: { Args: { p_report_id: string; p_kind: string; p_resource_id: string }; Returns: undefined };
      list_daily_report_resources: { Args: { p_report_id: string; p_linked?: boolean; p_offset?: number; p_limit?: number }; Returns: { resource_id: string; kind: string; label: string; quantity: number; unit: string; reversed: boolean; site_known: boolean; cost: number | null; total_count: number }[] };
      list_inventory_balances: { Args: { p_query?: string; p_location_id?: string | null; p_kind?: string; p_low?: boolean; p_offset?: number; p_limit?: number }; Returns: { id: string; material_id: string; inventory_location_id: string; quantity_on_hand: number; reserved_quantity: number; available_quantity: number; updated_at: string; material: Json; total_count: number }[] };
      set_employee_attendance_basis: { Args: { p_employee_id: string; p_rate_type: LaborRateType }; Returns: undefined };
      get_attendance_rate_basis: { Args: { p_employee_id: string; p_work_date: string }; Returns: LaborRateType };
      get_project_attendance_operations: { Args: { p_project_id: string; p_offset?: number; p_limit?: number }; Returns: { id: string; employee_id: string; assignment_id: string; project_id: string; project_site_id: string; work_date: string; attendance_status: string; hours_worked: number; note: string; created_at: string; reversed: boolean; total_count: number }[] };
      assign_initial_user_role: { Args: { p_user_id: string; p_role: AppRole }; Returns: undefined };
      set_managed_user_active: { Args: { p_user_id: string; p_is_active: boolean }; Returns: undefined };
      archive_project: { Args: { p_project_id: string }; Returns: ProjectRow };
      save_material_category: { Args: { p_id: string | null; p_name: string; p_description: string }; Returns: string };
      archive_material_category: { Args: { p_id: string }; Returns: undefined };
      save_material: { Args: { p_id: string | null; p_code: string; p_name: string; p_description: string; p_category_id: string; p_base_unit_id: string; p_material_kind: MaterialKind; p_minimum_stock_level: number | string; p_is_active: boolean }; Returns: string };
      archive_material: { Args: { p_id: string }; Returns: undefined };
      post_stock_in: { Args: { p_idempotency_key: string; p_material_id: string; p_destination_location_id: string; p_quantity: number | string; p_unit_id: string; p_reference_document: string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      post_valued_stock_in: { Args: { p_idempotency_key: string; p_material_id: string; p_destination_location_id: string; p_quantity: number | string; p_unit_id: string; p_total_cost: number | string; p_reference_document: string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      verify_opening_stock_value: { Args: { p_idempotency_key: string; p_material_id: string; p_location_id: string; p_quantity: number | string; p_total_value: number | string; p_reason: string }; Returns: string };
      consume_site_material: { Args: { p_idempotency_key: string; p_material_id: string; p_site_location_id: string; p_project_id: string; p_quantity: number | string; p_unit_id: string; p_reference_document: string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      get_project_material_cost: { Args: { p_project_id: string }; Returns: { material_id: string; material_code: string; material_name: string; quantity: number; unit_symbol: string; cost_total: number }[] };
      approve_transfer_variance: { Args: { p_idempotency_key: string; p_transfer_item_id: string; p_quantity: number | string; p_reason: string }; Returns: string };
      post_stock_out: { Args: { p_idempotency_key: string; p_material_id: string; p_source_location_id: string; p_quantity: number | string; p_unit_id: string; p_reference_document: string; p_transaction_date: string; p_project_id?: string | null; p_remarks?: string | null }; Returns: string };
      dispatch_inventory_transfer: { Args: { p_idempotency_key: string; p_material_id: string; p_source_location_id: string; p_destination_location_id: string; p_quantity: number | string; p_unit_id: string; p_external_reference: string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      receive_inventory_transfer: { Args: { p_idempotency_key: string; p_transfer_item_id: string; p_quantity: number | string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      reverse_inventory_transaction: { Args: { p_idempotency_key: string; p_transaction_id: string; p_reason: string }; Returns: string };
      submit_material_request: { Args: { p_idempotency_key: string; p_project_id: string; p_project_site_id: string; p_source_warehouse_id: string; p_required_date: string; p_purpose: string; p_lines: Json }; Returns: string };
      decide_material_request: { Args: { p_idempotency_key: string; p_request_id: string; p_decisions: Json; p_reason?: string | null }; Returns: string };
      cancel_material_request: { Args: { p_idempotency_key: string; p_request_id: string; p_reason: string }; Returns: string };
      get_requestable_warehouses: { Args: Record<string, never>; Returns: { project_id: string; warehouse_id: string; code: string; name: string }[] };
      get_material_request_context: { Args: { p_request_ids: string[] }; Returns: { request_id: string; project_id: string; project_code: string; project_name: string; site_id: string; site_name: string }[] };
      get_approved_request_queue: { Args: { p_limit?: number; p_offset?: number }; Returns: ApprovedRequestQueueRow[] };
      dispatch_approved_request_line: { Args: { p_idempotency_key: string; p_request_line_id: string; p_quantity: number | string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      receive_request_transfer: { Args: { p_idempotency_key: string; p_transfer_item_id: string; p_quantity: number | string; p_transaction_date: string; p_remarks?: string | null }; Returns: string };
      save_asset_category: { Args: { p_id: string | null; p_asset_kind: AssetKind; p_name: string; p_description: string }; Returns: string };
      archive_asset_category: { Args: { p_id: string }; Returns: undefined };
      save_asset_location: { Args: { p_id: string | null; p_location_kind: AssetLocationKind; p_name: string; p_address: string }; Returns: string };
      archive_asset_location: { Args: { p_id: string }; Returns: undefined };
      save_equipment: { Args: { p_id: string | null; p_code: string; p_name: string; p_description: string; p_category_id: string; p_brand: string; p_model: string; p_acquisition_date: string; p_ownership_type: AssetOwnershipType; p_status: AssetStatus; p_location_id: string; p_condition_notes: string; p_equipment_type: string; p_serial_number: string; p_acquisition_cost: number | string }; Returns: string };
      save_equipment_with_sku: { Args: { p_id: string | null; p_code: string; p_name: string; p_description: string; p_category_id: string; p_brand: string; p_model: string; p_acquisition_date: string; p_ownership_type: AssetOwnershipType; p_status: AssetStatus; p_location_id: string; p_condition_notes: string; p_equipment_type: string; p_serial_number: string; p_acquisition_cost: number | string; p_sku: string }; Returns: string };
      save_vehicle: { Args: { p_id: string | null; p_code: string; p_name: string; p_description: string; p_category_id: string; p_brand: string; p_model: string; p_acquisition_date: string; p_ownership_type: AssetOwnershipType; p_status: AssetStatus; p_location_id: string; p_condition_notes: string; p_plate_number: string; p_manufacture_year: number; p_current_mileage: number | string }; Returns: string };
      archive_asset: { Args: { p_id: string; p_reason: string }; Returns: undefined };
      get_requestable_equipment: { Args: { p_project_id: string; p_project_site_id: string }; Returns: { asset_id: string; asset_code: string; asset_name: string; asset_kind: AssetKind }[] };
      submit_equipment_request: { Args: { p_asset_id: string; p_project_id: string; p_project_site_id: string; p_needed_on: string; p_expected_return_on: string; p_purpose: string }; Returns: string };
      decide_equipment_request: { Args: { p_id: string; p_approve: boolean; p_note: string }; Returns: undefined };
      checkout_equipment_request: { Args: { p_id: string }; Returns: undefined };
      return_equipment_request: { Args: { p_id: string; p_needs_maintenance: boolean; p_note: string }; Returns: undefined };
      save_employee_category: { Args: { p_id: string | null; p_name: string; p_description: string }; Returns: string };
      archive_employee_category: { Args: { p_id: string }; Returns: undefined };
      save_employee: { Args: { p_id: string | null; p_code: string; p_first_name: string; p_middle_name: string; p_last_name: string; p_contact_number: string; p_category_id: string; p_employment_type: string; p_status: EmployeeStatus; p_hire_date: string; p_profile_id: string | null }; Returns: string };
      save_employee_with_email: { Args: { p_id: string | null; p_code: string; p_first_name: string; p_middle_name: string; p_last_name: string; p_contact_number: string; p_email_address: string; p_category_id: string; p_employment_type: string; p_status: EmployeeStatus; p_hire_date: string; p_profile_id: string | null }; Returns: string };
      archive_employee: { Args: { p_id: string; p_reason: string }; Returns: undefined };
      assign_employee_to_project: { Args: { p_employee_id: string; p_project_id: string; p_project_site_id: string; p_position_title: string; p_start_date: string; p_remarks: string }; Returns: string };
      end_employee_project_assignment: { Args: { p_assignment_id: string; p_end_date: string; p_remarks: string }; Returns: undefined };
      transfer_employee_assignment: { Args: { p_assignment_id: string; p_new_project_id: string; p_new_project_site_id: string; p_new_position_title: string; p_current_end_date: string; p_new_start_date: string; p_remarks: string }; Returns: string };
      post_labor_rate: { Args: { p_employee_id: string; p_rate_type: LaborRateType; p_rate_amount: number | string; p_effective_start_date: string; p_effective_end_date: string | null }; Returns: string };
      close_labor_rate: { Args: { p_rate_id: string; p_effective_end_date: string }; Returns: undefined };
      save_supplier_category: { Args: { p_id: string | null; p_name: string; p_description: string }; Returns: string };
      archive_supplier_category: { Args: { p_id: string }; Returns: undefined };
      save_supplier: { Args: { p_id: string | null; p_code: string; p_supplier_name: string; p_business_name: string; p_category_id: string; p_contact_person: string; p_contact_number: string; p_email_address: string; p_business_address: string; p_city: string; p_province: string; p_tax_identification_number: string; p_payment_terms: string; p_status: SupplierStatus; p_remarks: string }; Returns: string };
      archive_supplier: { Args: { p_id: string; p_reason: string }; Returns: undefined };
      save_supplier_material: { Args: { p_id: string | null; p_supplier_id: string; p_material_id: string; p_supplier_material_code: string; p_unit_id: string; p_minimum_order_quantity: number | string; p_lead_time_days: number | null; p_availability_status: MaterialAvailabilityStatus }; Returns: string };
      archive_supplier_material: { Args: { p_id: string }; Returns: undefined };
      post_supplier_price: { Args: { p_supplier_material_id: string; p_unit_price: number | string; p_effective_start_date: string; p_effective_end_date: string | null; p_currency: string }; Returns: string };
      close_supplier_price: { Args: { p_price_id: string; p_effective_end_date: string }; Returns: undefined };
      issue_client_invoice: { Args: { p_idempotency_key: string; p_project_id: string; p_description: string; p_issued_on: string; p_due_on: string; p_amount: number | string }; Returns: string };
      record_client_payment: { Args: { p_idempotency_key: string; p_invoice_id: string; p_amount: number | string; p_paid_on: string; p_reference: string }; Returns: string };
      reverse_client_payment: { Args: { p_idempotency_key: string; p_payment_id: string; p_reason: string }; Returns: string };
      void_client_invoice: { Args: { p_invoice_id: string; p_reason: string }; Returns: undefined };
      get_client_invoice_balances: { Args: { p_invoice_ids: string[] }; Returns: ClientInvoiceBalanceRow[] };
      get_billable_projects: { Args: Record<string, never>; Returns: { id: string; code: string; name: string; client_name: string; contract_amount: number; status: ProjectStatus }[] };
      issue_purchase_order: { Args: { p_idempotency_key: string; p_supplier_id: string; p_warehouse_id: string; p_ordered_on: string; p_expected_on: string; p_purpose: string; p_lines: Json }; Returns: string };
      receive_purchase_order_line: { Args: { p_idempotency_key: string; p_line_id: string; p_quantity: number | string; p_goods_total_cost: number | string; p_delivery_reference: string; p_received_on: string; p_cost_variance_reason?: string | null }; Returns: string };
      cancel_purchase_order: { Args: { p_order_id: string; p_reason: string }; Returns: undefined };
      post_project_attendance: { Args: { p_idempotency_key: string; p_assignment_id: string; p_work_date: string; p_status: "present" | "absent"; p_hours: number | string; p_rate_type: LaborRateType | null; p_day_fraction: number | string | null; p_note: string }; Returns: string };
      reverse_project_attendance: { Args: { p_idempotency_key: string; p_attendance_id: string; p_reason: string }; Returns: string };
      get_project_labor_cost: { Args: { p_project_id: string }; Returns: number };
      set_equipment_hour_rate: { Args: { p_asset_id: string; p_hourly_rate: number | string; p_effective_start_date: string }; Returns: string };
      post_project_equipment_usage: { Args: { p_idempotency_key: string; p_project_id: string; p_asset_id: string; p_use_date: string; p_hours: number | string; p_work_note: string }; Returns: string };
      post_project_equipment_usage_with_photos: { Args: { p_idempotency_key: string; p_project_id: string; p_asset_id: string; p_use_date: string; p_hours: number | string; p_work_note: string }; Returns: string };
      post_project_additional_expense: { Args: { p_idempotency_key: string; p_project_id: string; p_expense_date: string; p_category: string; p_description: string; p_external_reference: string; p_amount: number | string }; Returns: string };
      adjust_project_budget: { Args: { p_idempotency_key: string; p_project_id: string; p_change_amount: number | string; p_reason: string }; Returns: string };
      reverse_project_cost_entry: { Args: { p_idempotency_key: string; p_kind: "equipment" | "expense"; p_entry_id: string; p_reason: string }; Returns: string };
      get_project_management_summary: { Args: { p_project_id: string }; Returns: ProjectManagementSummaryRow[] };
      get_project_profitability: { Args: { p_project_id: string }; Returns: ProjectProfitabilityRow[] };
      get_dashboard_monthly_project_costs: { Args: { p_months?: number }; Returns: DashboardMonthlyCostRow[] };
      get_dashboard_totals: { Args: Record<string, never>; Returns: { total_sales: number; total_expenses: number | null; total_material_value: number | null; unvalued_stock: number; unvalued_expenses: number }[] };
      get_project_material_plan: { Args: { p_project_id: string }; Returns: ProjectMaterialPlanView[] };
      get_project_material_estimate: { Args: { p_project_id: string }; Returns: ProjectMaterialEstimateView[] };
      get_asset_photo_paths: { Args: { p_asset_ids: string[] }; Returns: { asset_id: string; photo_path: string }[] };
      save_project_material_plan_line: { Args: { p_project_id: string; p_site_id: string; p_warehouse_id: string; p_material_id: string; p_quantity: number | string; p_required_on: string; p_note: string }; Returns: string };
      record_project_progress: { Args: { p_report_id: string; p_percent: number | string; p_summary: string }; Returns: string };
      record_inventory_stock_count: { Args: { p_key: string; p_material_id: string; p_location_id: string; p_counted: number | string; p_reason_type: "physical_count" | "damaged" | "missing"; p_reason: string }; Returns: string };
      decide_inventory_stock_count: { Args: { p_count_id: string; p_approve: boolean; p_note: string }; Returns: string };
      get_unvalued_legacy_transit_queue: { Args: Record<string, never>; Returns: LegacyTransitQueueRow[] };
      verify_legacy_transit_value: { Args: { p_idempotency_key: string; p_transfer_item_id: string; p_dispatched_total_cost: number | string; p_received_total_cost: number | string; p_supporting_reference: string; p_reason: string }; Returns: string };
        save_daily_report: { Args: { p_id: string; p_project_id: string; p_project_site_id: string; p_report_date: string; p_weather_conditions: string; p_work_description: string; p_accomplishments: string; p_issues_encountered: string; p_site_observations: string; p_general_remarks: string; p_submit: boolean }; Returns: string };
        attach_daily_report_photo: { Args: { p_report_id: string }; Returns: undefined };
        review_daily_report: { Args: { p_report_id: string; p_action: "approve" | "return"; p_note: string }; Returns: string };
        start_daily_report_correction: { Args: { p_report_id: string }; Returns: string };
        attach_material_photo: { Args: { p_material_id: string }; Returns: undefined };
        attach_supplier_photo: { Args: { p_supplier_id: string }; Returns: undefined };
        attach_asset_photo: { Args: { p_asset_id: string }; Returns: undefined };
      ensure_qr_code: { Args: { p_entity_type: QrEntityType; p_entity_id: string }; Returns: string };
      deactivate_qr_code: { Args: { p_qr_id: string; p_reason: string }; Returns: undefined };
      replace_qr_code: { Args: { p_qr_id: string; p_reason: string }; Returns: string };
      resolve_mobile_qr_code: { Args: { p_identifier: string }; Returns: Json };
      resolve_qr_code: { Args: { p_identifier: string }; Returns: Json };
      get_unread_notification_count: { Args: Record<string, never>; Returns: number };
      mark_notification_read: { Args: { p_notification_id: string }; Returns: boolean };
      mark_all_notifications_read: { Args: Record<string, never>; Returns: number };
      mark_all_notifications_unread: { Args: Record<string, never>; Returns: number };
    };
    Enums: { app_role: AppRole; project_status: ProjectStatus; project_document_category: ProjectDocumentCategory; assignment_role: AssignmentRole; assignment_status: AssignmentStatus; warehouse_status: WarehouseStatus; site_status: "active" | "inactive"; inventory_location_type: "warehouse" | "project_site"; material_kind: MaterialKind; uom_dimension: UnitRow["dimension"]; inventory_transaction_type: InventoryTransactionType; material_request_status: MaterialRequestStatus; transfer_status: InventoryTransferRow["status"]; transfer_phase: "dispatch" | "receipt"; asset_kind: AssetKind; asset_ownership_type: AssetOwnershipType; asset_status: AssetStatus; asset_location_kind: AssetLocationKind; asset_event_type: AssetEventType; employee_status: EmployeeStatus; workforce_assignment_status: WorkforceAssignmentStatus; labor_rate_type: LaborRateType; employee_event_type: EmployeeEventType; supplier_status: SupplierStatus; material_availability_status: MaterialAvailabilityStatus; supplier_event_type: SupplierEventType; daily_report_status: DailyReportStatus; daily_report_event_type: DailyReportEventType; qr_entity_type: QrEntityType; qr_status: QrStatus; qr_event_type: QrEventRow["event_type"]; notification_priority: NotificationPriority; notification_outbox_status: NotificationOutboxStatus };
    CompositeTypes: Record<string, never>;
  };
};
