import { ListFilterBar } from "@/components/ui/list-filter-bar";
import Link from "next/link";
import { ReversalForm } from "@/components/inventory/transaction-action-form";
import { Button } from "@/components/ui/button";
import { DataTableShell } from "@/components/ui/data-table-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { requireUser } from "@/lib/auth";
import { getInventoryTransactions } from "@/lib/data/inventory";
import type { InventoryTransactionType } from "@/types/database";
const types: Array<InventoryTransactionType | "all"> = ["all", "STOCK_IN", "STOCK_OUT", "WAREHOUSE_TRANSFER", "SITE_TRANSFER", "REVERSAL"];
export default async function TransactionsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const params = await searchParams; const type = typeof params.type === "string" && types.includes(params.type as typeof types[number]) ? params.type as typeof types[number] : "all"; const locationId = typeof params.location === "string" ? params.location : ""; const reverseId = typeof params.reverse === "string" ? params.reverse : ""; const [user, data] = await Promise.all([requireUser(), getInventoryTransactions({ type, locationId })]); const reversible = user.canManage ? data.transactions.find((item) => item.id === reverseId && item.transaction_type !== "REVERSAL" && !item.reversal_of) : undefined; return <>
  <PageHeader title="Stock history" description="Stock in, stock out, transfers and usage are recorded automatically. Corrections preserve the original record." action={<div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link href={`/inventory/counts?${new URLSearchParams(locationId ? { location: locationId } : {})}`}>Check stock</Link></Button><Button variant="outline" asChild><Link href="/inventory">Back to inventory</Link></Button></div>} />
  <div className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white">{reversible && <ReversalForm transactionId={reversible.id} />}<ListFilterBar className="grid gap-3 p-4 md:grid-cols-[220px_1fr_auto]"><select name="type" defaultValue={type} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="all">All transaction types</option>{types.slice(1).map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><select name="location" defaultValue={locationId} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All authorized locations</option>{data.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></ListFilterBar></div>
  <DataTableShell empty={data.transactions.length === 0 ? <EmptyState kind="results" title="No matching transactions" description="Try another date, material, or transaction type." /> : undefined}><table className="w-full min-w-[1180px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-5 py-3">Date / type</th><th className="px-4 py-3">Material</th><th className="px-4 py-3 text-right">Quantity</th><th className="px-4 py-3">Movement</th><th className="px-4 py-3">Reference / remarks</th><th className="px-4 py-3">Project / responsible</th>{user.canManage && <th className="px-5 py-3 text-right">Correction</th>}</tr></thead><tbody className="divide-y divide-slate-100">{data.transactions.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="text-xs font-semibold">{item.transaction_type.replaceAll("_", " ")}</p><p className="mt-1 text-[11px] text-slate-400">{item.transaction_date}</p></td><td className="px-4 py-4"><p className="text-sm font-semibold">{item.material?.name ?? "Unavailable"}</p><p className="text-[11px] text-slate-400">{item.material?.code}</p></td><td className="px-4 py-4 text-right text-sm font-semibold tabular-nums">{item.quantity} {item.unitSymbol}</td><td className="px-4 py-4 text-xs text-slate-600">{item.source?.name ?? "External"} → {item.destination?.name ?? "External"}{item.transfer_phase && <span className="mt-1 block capitalize text-slate-400">{item.transfer_phase}</span>}</td><td className="px-4 py-4 text-xs text-slate-600"><p className="font-medium text-slate-800">{item.reference_document}</p><p className="mt-1 max-w-56 truncate text-slate-400">{item.remarks || "No remarks"}</p></td><td className="px-4 py-4 text-xs text-slate-600"><p>{item.project ? `${item.project.code} · ${item.project.name}` : "No project"}</p><p className="mt-1 text-slate-400">{item.responsibleName}</p></td>{user.canManage && <td className="px-5 py-4 text-right">{item.transaction_type !== "REVERSAL" && !item.reversal_of && <Button variant="ghost" size="sm" asChild><Link href={`/inventory/transactions?reverse=${item.id}`}>Reverse</Link></Button>}</td>}</tr>)}</tbody></table></DataTableShell>
  </>; }
