import { HistoryPagination } from "@/components/ui/history-pagination";
import { IntentLink as Link } from "@/components/layout/intent-link";
import { RecordCreateDialog } from "@/components/ui/record-create-dialog";
import { PhotoViewer } from "@/components/ui/photo-viewer";
import { recordPhotoUrl } from "@/lib/media/record-photo-url";
import { AssetForm } from "./asset-form";
import { ArchiveAssetForm } from "@/components/assets/archive-asset-form";
import { AssetStatusBadge } from "@/components/assets/asset-status-badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { EntityQrSection } from "@/components/qr/entity-qr-section";
import type { getAsset, getEquipmentUsage, getAssetReferences } from "@/lib/data/assets";
import type { AssetKind } from "@/types/database";

type AssetDetailData = Awaited<ReturnType<typeof getAsset>>;
type EquipmentUsageData = Awaited<ReturnType<typeof getEquipmentUsage>>;
export function AssetDetail({ data, kind, canManage, usage, references, editing = false }: { data: AssetDetailData; kind: AssetKind; canManage: boolean; usage?: EquipmentUsageData; references?: Awaited<ReturnType<typeof getAssetReferences>>; editing?: boolean }) { const { asset, events } = data; const isEquipment = kind === "equipment"; const base = isEquipment ? "/equipment" : "/vehicles"; const detailRows = isEquipment ? [["Equipment type", asset.equipment?.equipment_type], ["Serial number", asset.equipment?.serial_number], ["Acquisition cost", asset.equipment ? `₱${Number(asset.equipment.acquisition_cost).toLocaleString("en-PH", { minimumFractionDigits: 2 })}` : "—"]] : [["Vehicle type", asset.categoryName], ["Plate number", asset.vehicle?.plate_number], ["Manufacture year", asset.vehicle?.manufacture_year], ["Current mileage", asset.vehicle ? `${Number(asset.vehicle.current_mileage).toLocaleString()} km` : "—"]]; return <>
  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700">{isEquipment ? "Equipment registry" : "Vehicle registry"}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-[-0.035em]">{asset.name}</h1><AssetStatusBadge status={asset.status} /></div><p className="mt-1 text-sm text-slate-500">{asset.code} · {asset.categoryName}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link href={base}>Back</Link></Button>{isEquipment && !asset.archived_at && <Button variant="outline" asChild><Link href="/equipment/requests">Requests and handovers</Link></Button>}{canManage && !asset.archived_at && !["assigned", "in_use"].includes(asset.status) && references && <RecordCreateDialog title={`Edit ${kind}`} triggerLabel="Edit" triggerVariant="outline" initialOpen={editing} closeHref={`${base}/${asset.id}`}><AssetForm kind={kind} asset={asset} {...references} /></RecordCreateDialog>}</div></div>
  {asset.photo_path && <div className="mt-5 h-52 overflow-hidden rounded-2xl sm:h-72"><PhotoViewer src={recordPhotoUrl("assets", asset.id, asset.updated_at)} alt={`${asset.name} photo`} /></div>}
  <EntityQrSection entityType={kind} entityId={asset.id} canManage={canManage} />
  <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="grid divide-y divide-slate-100 md:grid-cols-2 md:divide-x md:divide-y-0"><div className="p-5 sm:p-6"><h2 className="font-semibold">Registry details</h2><dl className="mt-5 grid grid-cols-[145px_1fr] gap-x-5 gap-y-4 text-sm">{[["Classification", asset.categoryName], ["Brand", asset.brand], ["Model", asset.model], ...detailRows, ["Ownership", asset.ownership_type.replaceAll("_", " ")], ["Acquired", asset.acquisition_date]].map(([label, value]) => <div className="contents" key={String(label)}><dt className="text-slate-400">{label}</dt><dd className="font-medium capitalize text-slate-700">{value ?? "—"}</dd></div>)}</dl></div><div className="p-5 sm:p-6"><h2 className="font-semibold">Location and condition</h2><p className="mt-5 text-sm font-semibold text-slate-800">{asset.location?.displayName ?? "Unavailable location"}</p><p className="mt-1 text-xs text-slate-500">{asset.location?.displayAddress}</p><p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Condition notes</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{asset.condition_notes || "No condition notes recorded."}</p><p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Description</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{asset.description || "No description recorded."}</p>{canManage && !asset.archived_at && <RecordCreateDialog title={`Delete ${kind}`} triggerLabel="Delete" triggerVariant="outline"><ArchiveAssetForm id={asset.id} kind={kind} /></RecordCreateDialog>}</div></div></section>
  <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Registry history</h2><p className="mt-1 text-xs text-slate-500">Administrative, status, and location changes are append-only.</p></div>{events.length === 0 ? <EmptyState compact kind="items" title="No history available" /> : <ol className="divide-y divide-slate-100">{events.map((event) => <li key={event.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[150px_1fr_auto]"><div><p className="text-xs font-semibold capitalize text-slate-700">{event.event_type.replaceAll("_", " ")}</p><time className="text-[11px] text-slate-400">{new Date(event.occurred_at).toLocaleString("en-PH", { timeZone: "Asia/Manila" })}</time></div><div><p className="text-sm text-slate-700">{event.summary}</p>{event.previousLocation?.displayName !== event.currentLocation?.displayName && <p className="mt-1 text-xs text-slate-400">{event.previousLocation?.displayName ?? "None"} → {event.currentLocation?.displayName ?? "None"}</p>}</div><p className="text-xs text-slate-400">{event.actorName}</p></li>)}</ol>}<div className="p-4"><HistoryPagination path={`${base}/${asset.id}`} parameter="eventPage" page={data.eventPage} count={data.eventCount} filters={{ usagePage: String(usage?.page ?? 1) }} /></div></section>
  {usage && <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Project usage and cost</h2><p className="mt-1 text-xs text-slate-500">{usage.count} posted entries · 20 per page. Financial details are restricted to authorized roles.</p></div>{!usage.rows.length ? <EmptyState compact kind="items" title="No usage recorded" /> : <div className="overflow-x-auto"><table className="w-full min-w-[690px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">Date</th><th className="px-4 py-3">Project</th><th className="px-4 py-3 text-right">Hours</th><th className="px-4 py-3 text-right">Rate</th><th className="px-5 py-3 text-right">Cost</th></tr></thead><tbody className="divide-y divide-slate-100">{usage.rows.map((entry) => <tr key={entry.id}><td className="px-5 py-3">{entry.use_date}</td><td className="px-4 py-3"><span className="font-medium">{entry.projectName}</span>{entry.work_note && <span className="mt-1 block text-xs text-slate-500">{entry.work_note}</span>}{entry.reversal && <span className="mt-1 block text-xs text-red-700">Reversed: {entry.reversal.reason}</span>}</td><td className="px-4 py-3 text-right tabular-nums">{entry.hours_used}</td><td className="px-4 py-3 text-right tabular-nums">₱{Number(entry.hourly_rate_snapshot).toLocaleString("en-PH", { minimumFractionDigits: 2 })}</td><td className="px-5 py-3 text-right font-semibold tabular-nums">{entry.reversal ? "—" : `₱${Number(entry.cost_total).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`}</td></tr>)}</tbody></table></div>}<div className="p-4"><HistoryPagination path={`${base}/${asset.id}`} parameter="usagePage" page={usage.page} count={usage.count} filters={{ eventPage: String(data.eventPage) }} /></div></section>}
  </>; }
