import Link from "next/link";
import { Download04Icon, PlusSignIcon, Search01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { assetStatuses } from "@nognog/domain";
import { AssetTable } from "@/components/assets/asset-table";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/ui/page-header";
import { requireUser } from "@/lib/auth";
import { getAssetReferences, getAssets } from "@/lib/data/assets";
import type { AssetKind, AssetStatus } from "@/types/database";

const statuses: Array<AssetStatus | "all"> = ["all", ...assetStatuses];
export async function AssetRegistryPage({ kind, searchParams }: { kind: AssetKind; searchParams: Promise<Record<string, string | string[] | undefined>> }) { const params = await searchParams; const query = typeof params.q === "string" ? params.q : ""; const categoryId = typeof params.category === "string" ? params.category : ""; const locationId = typeof params.location === "string" ? params.location : ""; const status = typeof params.status === "string" && statuses.includes(params.status as typeof statuses[number]) ? params.status as typeof statuses[number] : "all"; const [user, assets, references] = await Promise.all([requireUser(), getAssets({ kind, query, categoryId, locationId, status, includeArchived: status === "retired" }), getAssetReferences(kind)]); const isEquipment = kind === "equipment"; const base = isEquipment ? "/equipment" : "/vehicles"; const exportParams = new URLSearchParams(); if (query) exportParams.set("q", query); if (categoryId) exportParams.set("category", categoryId); if (locationId) exportParams.set("location", locationId); if (status !== "all") exportParams.set("status", status); const exportHref = `${base}/export?${exportParams.toString()}`; return <>
  <PageHeader eyebrow="Reusable asset control" title={isEquipment ? "Equipment" : "Vehicles"} description={isEquipment ? "Availability, location, condition, and registry history without mixing assets into material stock." : "A shared asset identity for fleet records, mileage, status, and current location."} action={<div className="flex flex-wrap gap-2">{isEquipment && <><Button variant="outline" asChild><Link href="/equipment/requests">Equipment requests</Link></Button><Button variant="outline" asChild><Link href={exportHref}><HugeiconsIcon icon={Download04Icon} size={17} />Export CSV</Link></Button></>}{user.canManage && <><Button variant="outline" asChild><Link href="/equipment/categories">Classifications</Link></Button>{isEquipment && <Button variant="outline" asChild><Link href="/equipment/locations">Locations</Link></Button>}<Button asChild><Link href={`${base}/new`}><HugeiconsIcon icon={PlusSignIcon} size={17} /> {isEquipment ? "Add equipment" : "Add vehicle"}</Link></Button></>}</div>} />
  <form className="mt-7 grid gap-3 border-y border-slate-200 bg-white p-4 lg:grid-cols-[1fr_210px_210px_190px_auto]"><label className="relative"><span className="sr-only">Search {kind}</span><HugeiconsIcon icon={Search01Icon} size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input name="q" defaultValue={query} placeholder={`Search ${kind}, code, brand, or model`} className="h-10 w-full rounded-full border border-slate-200 pl-11 pr-4 text-sm" /></label><select name="category" defaultValue={categoryId} aria-label="Classification" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All classifications</option>{references.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="location" defaultValue={locationId} aria-label="Current location" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All locations</option>{references.locations.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select><select name="status" defaultValue={status} aria-label="Operational status" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm">{statuses.map((item) => <option key={item} value={item}>{item === "all" ? "All statuses" : item.replaceAll("_", " ")}</option>)}</select><Button variant="outline">Apply</Button></form>
  <AssetTable assets={assets} kind={kind} />
  </>; }
