import Link from "next/link";
import { PlusSignIcon, Search01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DataTableShell } from "@/components/ui/data-table-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { requireUser } from "@/lib/auth";
import { getMaterialReferences, getMaterials } from "@/lib/data/inventory";
export default async function MaterialsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const params = await searchParams; const query = typeof params.q === "string" ? params.q : ""; const categoryId = typeof params.category === "string" ? params.category : ""; const status = params.status === "inactive" ? "inactive" : params.status === "all" ? "all" : "active"; const [user, materials, references] = await Promise.all([requireUser(), getMaterials({ query, categoryId, status }), getMaterialReferences()]); return <>
  <PageHeader eyebrow="Inventory catalog" title="Materials" description="Maintain one reusable material catalog with explicit units and categories." action={user.canManage && <div className="flex gap-2"><Button variant="outline" asChild><Link href="/materials/categories">Categories</Link></Button><Button asChild><Link href="/materials/new"><HugeiconsIcon icon={PlusSignIcon} size={17} /> New material</Link></Button></div>} />
  <form className="mt-7 grid gap-3 border-y border-slate-200 bg-white p-4 md:grid-cols-[1fr_220px_160px_auto]"><label className="relative"><span className="sr-only">Search materials</span><HugeiconsIcon icon={Search01Icon} size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input name="q" defaultValue={query} placeholder="Search code or material" className="h-10 w-full rounded-lg border border-slate-200 pl-10 pr-3 text-sm" /></label><select name="category" defaultValue={categoryId} aria-label="Category" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All categories</option>{references.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="status" defaultValue={status} aria-label="Status" className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select><Button variant="outline">Apply</Button></form>
  <DataTableShell empty={materials.length === 0 ? <EmptyState kind={query || categoryId || status !== "active" ? "results" : "items"} title="No materials found" description="Change the filters or register a material." /> : undefined}><table className="w-full min-w-[820px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-5 py-3">Material</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Base unit</th><th className="px-4 py-3">Minimum</th><th className="px-4 py-3">Type</th><th className="px-5 py-3 text-right">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{materials.map((item) => <tr key={item.id} className="hover:bg-slate-50/60"><td className="px-5 py-4"><Link href={`/materials/${item.id}`} className="text-sm font-semibold text-slate-800 hover:text-cyan-700">{item.name}</Link><p className="mt-0.5 text-[11px] text-slate-400">{item.code}</p></td><td className="px-4 py-4 text-xs text-slate-600">{item.categoryName}</td><td className="px-4 py-4 text-xs text-slate-600">{item.unitName}</td><td className="px-4 py-4 text-xs tabular-nums text-slate-600">{item.minimum_stock_level} {item.unitSymbol}</td><td className="px-4 py-4 text-xs capitalize text-slate-600">{item.material_kind}</td><td className="px-5 py-4 text-right"><Badge variant={item.is_active ? "active" : "neutral"}>{item.is_active ? "Active" : "Inactive"}</Badge></td></tr>)}</tbody></table></DataTableShell>
  </>; }
