import { HistoryPagination } from "@/components/ui/history-pagination";
import { pageNumber } from "@/lib/data/pagination";
import { IntentLink as Link } from "@/components/layout/intent-link";
import { ArchiveSupplierForm } from "@/components/suppliers/supplier-catalog-forms";
import { SupplierPhoto } from "@/components/suppliers/supplier-photo";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { RecordCreateDialog } from "@/components/ui/record-create-dialog";
import { SupplierForm } from "@/components/suppliers/supplier-form";
import { requireProcurementViewer } from "@/lib/auth";
import { getSupplier } from "@/lib/data/suppliers";
import { getSupplierPayments } from "@/lib/data/purchase-orders";

const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "Present";
const dateTime = (value: string) => new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const money = (amount: number, currency: string) => new Intl.NumberFormat("en-PH", { style: "currency", currency, maximumFractionDigits: 2 }).format(amount);

export default async function SupplierDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ edit?: string; eventsPage?: string; purchasesPage?: string; pricesPage?: string; paymentsPage?: string }> }) {
  const { id } = await params; const query = await searchParams;
  const pages = { events: pageNumber(query.eventsPage), purchases: pageNumber(query.purchasesPage), prices: pageNumber(query.pricesPage) };
  const paymentsPage = pageNumber(query.paymentsPage);
  const [user, data, payments] = await Promise.all([requireProcurementViewer(), getSupplier(id, pages), getSupplierPayments(id, paymentsPage)]);
  const today = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Manila", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const { supplier, category, catalog, events, priceActors, purchaseOrders, purchaseOrderCount } = data;
  return <>
    <PageHeader eyebrow={supplier.code} title={supplier.supplier_name} description={[category?.name, supplier.business_name].filter(Boolean).join(" · ") || supplier.business_address} action={user.canManage && !supplier.archived_at && <RecordCreateDialog key={supplier.updated_at} title="Edit supplier" triggerLabel="Edit supplier" triggerVariant="outline" initialOpen={query.edit === "1"} closeHref={`/suppliers/${id}`}><SupplierForm supplier={supplier} categories={data.references.categories} /></RecordCreateDialog>} />
    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-4 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><SupplierPhoto name={supplier.supplier_name} photo={supplier.photo_path ? `/record-photos/suppliers/${supplier.id}` : null} className="size-16" sizes="64px" /><div><h2 className="font-semibold">Supplier record</h2><p className="mt-1 text-xs text-slate-500">Contact and address</p></div></div><Badge variant={supplier.archived_at ? "neutral" : supplier.status === "active" ? "active" : "review"}>{supplier.archived_at ? "archived" : supplier.status}</Badge></div><dl className="grid gap-x-8 gap-y-5 px-6 py-5 sm:grid-cols-2 xl:grid-cols-4"><div><dt className="text-xs text-slate-400">Contact person</dt><dd className="mt-1 text-sm font-medium">{supplier.contact_person ?? "—"}</dd></div><div><dt className="text-xs text-slate-400">Contact</dt><dd className="mt-1 text-sm font-medium">{supplier.contact_number}{supplier.email_address && <><br /><a className="text-cyan-700 hover:underline" href={`mailto:${supplier.email_address}`}>{supplier.email_address}</a></>}</dd></div><div><dt className="text-xs text-slate-400">Location</dt><dd className="mt-1 text-sm font-medium">{supplier.business_address}{supplier.city && <><br />{[supplier.city, supplier.province].filter(Boolean).join(", ")}</>}</dd></div><div><dt className="text-xs text-slate-400">Payment terms</dt><dd className="mt-1 text-sm font-medium">{supplier.payment_terms ?? "—"}</dd></div><div><dt className="text-xs text-slate-400">Tax ID</dt><dd className="mt-1 text-sm font-medium">{supplier.tax_identification_number || "Not recorded"}</dd></div>{supplier.remarks && <div className="sm:col-span-2 xl:col-span-3"><dt className="text-xs text-slate-400">Remarks</dt><dd className="mt-1 text-sm text-slate-600">{supplier.remarks}</dd></div>}</dl>{user.canManage && !supplier.archived_at && <div id="supplier-archive" className="scroll-mt-28 border-t border-slate-100 px-6 py-4"><ArchiveSupplierForm supplierId={id} /></div>}</section>

    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white" aria-labelledby="supplier-history-heading"><div className="border-b border-slate-100 px-6 py-5"><h2 id="supplier-history-heading" className="font-semibold">Supplier history</h2><p className="mt-1 text-xs text-slate-500">Payments made to this supplier</p></div>
      {payments.rows.length === 0 ? <EmptyState compact title="No payments yet" description="Payments recorded on this supplier's purchase orders appear here." /> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-6 py-3">Purchase</th><th className="px-4 py-3">Check</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Bank</th><th className="px-6 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.rows.map((payment) => <tr key={payment.id} className={payment.voided ? "text-slate-400" : undefined}><td className="px-6 py-3"><Link href={`/purchase-orders/${payment.purchase_order_id}`} className="font-medium text-cyan-700 hover:underline">{payment.poNumber}</Link></td><td className="px-4 py-3 tabular-nums">{payment.method === "check" ? payment.check_number : "Cash"}</td><td className={`px-4 py-3 text-right tabular-nums ${payment.voided ? "line-through" : "font-medium"}`}>{money(Number(payment.amount), "PHP")}</td><td className="px-4 py-3 tabular-nums">{date(payment.payment_date)}</td><td className="px-4 py-3">{payment.bank_name ?? "—"}</td><td className="px-6 py-3 text-xs">{payment.voided ? "Void" : payment.method === "check" && payment.payment_date > today ? <span className="rounded-full bg-amber-50 px-2 py-0.5 font-semibold text-amber-700">Postdated</span> : "Paid"}</td></tr>)}</tbody></table></div>}
      {payments.pageCount > 1 && <div className="px-6 pb-4"><HistoryPagination path={`/suppliers/${id}`} parameter="paymentsPage" page={payments.page} count={payments.count} filters={{ eventsPage: String(pages.events), purchasesPage: String(pages.purchases), pricesPage: String(pages.prices) }} /></div>}
    </section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-2 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Materials and prices</h2><p className="mt-1 text-xs text-slate-500">Prices come from purchases. The newest purchase price is the current price.</p></div><Button variant="outline" size="sm" asChild><Link href={`/suppliers/prices?supplier=${id}`}>Compare and filter prices</Link></Button></div>{!catalog.length ? <EmptyState compact kind="items" title="No materials yet" description="Materials appear here after the first purchase from this supplier." /> : <div className="divide-y divide-slate-100">{catalog.map((item) => { const current = item.prices.current; const previous = item.prices.previous; const difference = current && previous && current.currency === previous.currency ? current.unit_price - previous.unit_price : null; return <article key={item.id} className="px-6 py-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{item.material?.name ?? "Unavailable material"}</h3><Badge variant={item.archived_at ? "neutral" : item.availability_status === "available" ? "active" : item.availability_status === "limited" ? "review" : "neutral"}>{item.archived_at ? "archived" : item.availability_status}</Badge></div><p className="mt-1 text-xs text-slate-500">{item.material?.code ?? item.supplier_material_code} · per {item.unit?.symbol ?? "unit"}</p></div><div className="grid min-w-0 gap-3 sm:grid-cols-3 xl:min-w-[520px]"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Current</p><p className="mt-1 text-sm font-semibold">{current ? `${money(current.unit_price, current.currency)} / ${item.unit?.symbol ?? "unit"}` : "Not configured"}</p>{current && <p className="text-xs text-slate-400">Since {date(current.effective_start_date)}</p>}</div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Previous</p><p className="mt-1 text-sm font-semibold">{previous ? money(previous.unit_price, previous.currency) : "None"}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Change</p><p className={`mt-1 text-sm font-semibold ${difference !== null && difference > 0 ? "text-amber-700" : difference !== null && difference < 0 ? "text-emerald-700" : ""}`}>{difference === null ? "—" : `${difference > 0 ? "+" : ""}${money(difference, current?.currency ?? "PHP")}`}</p></div></div></div>
          {item.prices.history.length > 0 && <details className="mt-4 rounded-lg border border-slate-200"><summary className="cursor-pointer px-4 py-3 text-xs font-semibold text-slate-700">Price history ({item.prices.history.length})</summary><div className="divide-y divide-slate-100 border-t border-slate-100">{item.prices.history.map((price) => <div key={price.id} className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{money(price.unit_price, price.currency)} / {item.unit?.symbol ?? "unit"}</p><p className="mt-1 text-xs text-slate-400">{date(price.effective_start_date)} – {date(price.effective_end_date)} · {priceActors.get(price.recorded_by) ?? "Authorized user"}</p></div></div>)}</div></details>}
        </article>; })}</div>}</section>

    <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-semibold">Purchase history</h2><p className="mt-1 text-xs text-slate-500">{purchaseOrderCount} orders · 20 per page</p></div>{!purchaseOrders.length ? <EmptyState compact kind="items" title="No purchase orders" /> : <div className="max-h-[360px] divide-y divide-slate-100 overflow-y-auto">{purchaseOrders.map((order) => <Link key={order.id} href={`/purchase-orders/${order.id}`} className="flex items-start justify-between gap-3 px-6 py-4 hover:bg-slate-50"><div><p className="text-sm font-semibold text-slate-800">{order.po_number}</p><p className="mt-1 text-xs text-slate-500">{order.warehouse_name} · {date(order.ordered_on)} · {order.receiptCount} receipts</p></div><Badge variant={order.status === "received" ? "active" : order.status === "cancelled" ? "neutral" : "review"}>{order.status.replaceAll("_", " ")}</Badge></Link>)}</div>}</article><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-semibold">Supplier history</h2><p className="mt-1 text-xs text-slate-500">A history of changes to supplier details, products, and prices.</p></div>{!events.length ? <EmptyState compact kind="items" title="No history available" /> : <div className="max-h-[360px] divide-y divide-slate-100 overflow-y-auto">{events.map((event) => <div key={event.id} className="px-6 py-4"><p className="text-sm font-medium">{event.summary}</p><p className="mt-1 text-xs text-slate-400">{event.actorName} · {dateTime(event.occurred_at)}</p></div>)}</div>}</article></section>
    <div className="mt-5 grid gap-4 sm:grid-cols-3">{(["events", "purchases", "prices"] as const).map((kind) => <div key={kind}><h3 className="text-sm font-medium capitalize">{kind} history</h3><HistoryPagination path={`/suppliers/${id}`} parameter={`${kind}Page`} page={pages[kind]} count={kind === "purchases" ? purchaseOrderCount : data.historyCounts[kind]} filters={{ eventsPage: String(pages.events), purchasesPage: String(pages.purchases), pricesPage: String(pages.prices) }} /></div>)}</div>
  </>;
}
