import { IntentLink as Link } from "@/components/layout/intent-link";
import { PencilEdit02Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { ArchiveSupplierForm, ArchiveSupplierMaterialForm, CloseSupplierPriceForm, SupplierMaterialForm, SupplierPriceForm } from "@/components/suppliers/supplier-catalog-forms";
import { SupplierPhoto } from "@/components/suppliers/supplier-photo";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { requireProcurementViewer } from "@/lib/auth";
import { getSupplier } from "@/lib/data/suppliers";

const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "Present";
const dateTime = (value: string) => new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const money = (amount: number, currency: string) => new Intl.NumberFormat("en-PH", { style: "currency", currency, maximumFractionDigits: 2 }).format(amount);

export default async function SupplierDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ editCatalog?: string }> }) {
  const { id } = await params; const query = await searchParams;
  const [user, data] = await Promise.all([requireProcurementViewer(), getSupplier(id)]);
  const { supplier, category, catalog, events, priceActors, purchaseOrders, purchaseOrderCount, references } = data;
  const editing = user.canManage && query.editCatalog ? catalog.find((item) => item.id === query.editCatalog && !item.archived_at) : undefined;
  return <>
    <PageHeader eyebrow={supplier.code} title={supplier.supplier_name} description={`${category?.name ?? "Unavailable category"} · ${supplier.business_name}`} action={user.canManage && !supplier.archived_at && <Button variant="outline" asChild><Link href={`/suppliers/${id}/edit`}><HugeiconsIcon icon={PencilEdit02Icon} size={17} /> Edit supplier</Link></Button>} />
    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-4 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><SupplierPhoto name={supplier.supplier_name} photo={supplier.photo_path ? `/record-photos/suppliers/${supplier.id}` : null} className="size-16" sizes="64px" /><div><h2 className="font-semibold">Supplier record</h2><p className="mt-1 text-xs text-slate-500">Contact, location, and commercial reference information</p></div></div><Badge variant={supplier.archived_at ? "neutral" : supplier.status === "active" ? "active" : "review"}>{supplier.archived_at ? "archived" : supplier.status}</Badge></div><dl className="grid gap-x-8 gap-y-5 px-6 py-5 sm:grid-cols-2 xl:grid-cols-4"><div><dt className="text-xs text-slate-400">Contact person</dt><dd className="mt-1 text-sm font-medium">{supplier.contact_person}</dd></div><div><dt className="text-xs text-slate-400">Contact</dt><dd className="mt-1 text-sm font-medium">{supplier.contact_number}<br /><a className="text-cyan-700 hover:underline" href={`mailto:${supplier.email_address}`}>{supplier.email_address}</a></dd></div><div><dt className="text-xs text-slate-400">Location</dt><dd className="mt-1 text-sm font-medium">{supplier.business_address}<br />{supplier.city}, {supplier.province}</dd></div><div><dt className="text-xs text-slate-400">Payment terms</dt><dd className="mt-1 text-sm font-medium">{supplier.payment_terms}</dd></div><div><dt className="text-xs text-slate-400">Tax ID</dt><dd className="mt-1 text-sm font-medium">{supplier.tax_identification_number || "Not recorded"}</dd></div>{supplier.remarks && <div className="sm:col-span-2 xl:col-span-3"><dt className="text-xs text-slate-400">Remarks</dt><dd className="mt-1 text-sm text-slate-600">{supplier.remarks}</dd></div>}</dl>{user.canManage && !supplier.archived_at && <div id="supplier-archive" className="scroll-mt-28 border-t border-slate-100 px-6 py-4"><ArchiveSupplierForm supplierId={id} /></div>}</section>

    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-2 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Material catalog and price history</h2><p className="mt-1 text-xs text-slate-500">Each entry reuses the Phase 3 material master and its base unit.</p></div><Button variant="outline" size="sm" asChild><Link href={`/suppliers/prices?supplier=${id}`}>Compare and filter prices</Link></Button></div>{user.canManage && !supplier.archived_at && <div className="border-b border-slate-100 p-5"><SupplierMaterialForm supplierId={id} catalog={editing} materials={references.materials} units={references.units} /></div>}{!catalog.length ? <EmptyState compact kind="items" title="No supplier materials" /> : <div className="divide-y divide-slate-100">{catalog.map((item) => { const current = item.prices.current; const previous = item.prices.previous; const difference = current && previous && current.currency === previous.currency ? current.unit_price - previous.unit_price : null; return <article key={item.id} className="px-6 py-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{item.material?.name ?? "Unavailable material"}</h3><Badge variant={item.archived_at ? "neutral" : item.availability_status === "available" ? "active" : item.availability_status === "limited" ? "review" : "neutral"}>{item.archived_at ? "archived" : item.availability_status}</Badge></div><p className="mt-1 text-xs text-slate-500">{item.supplier_material_code} · MOQ {item.minimum_order_quantity} {item.unit?.symbol ?? ""} · {item.lead_time_days === null ? "Lead time not recorded" : `${item.lead_time_days} day lead time`}</p></div><div className="grid min-w-0 gap-3 sm:grid-cols-3 xl:min-w-[520px]"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Current</p><p className="mt-1 text-sm font-semibold">{current ? `${money(current.unit_price, current.currency)} / ${item.unit?.symbol ?? "unit"}` : "Not configured"}</p>{current && <p className="text-xs text-slate-400">Since {date(current.effective_start_date)}</p>}</div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Previous</p><p className="mt-1 text-sm font-semibold">{previous ? money(previous.unit_price, previous.currency) : "None"}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Change</p><p className={`mt-1 text-sm font-semibold ${difference !== null && difference > 0 ? "text-amber-700" : difference !== null && difference < 0 ? "text-emerald-700" : ""}`}>{difference === null ? "—" : `${difference > 0 ? "+" : ""}${money(difference, current?.currency ?? "PHP")}`}</p></div></div></div>
          {item.prices.history.length > 0 && <details className="mt-4 rounded-lg border border-slate-200"><summary className="cursor-pointer px-4 py-3 text-xs font-semibold text-slate-700">Price history ({item.prices.history.length})</summary><div className="divide-y divide-slate-100 border-t border-slate-100">{item.prices.history.map((price) => <div key={price.id} className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{money(price.unit_price, price.currency)} / {item.unit?.symbol ?? "unit"}</p><p className="mt-1 text-xs text-slate-400">{date(price.effective_start_date)} – {date(price.effective_end_date)} · {priceActors.get(price.recorded_by) ?? "Authorized user"}</p></div>{user.canManage && !price.effective_end_date && <CloseSupplierPriceForm supplierId={id} price={price} />}</div>)}</div></details>}
          {user.canManage && !item.archived_at && <div className="mt-4"><SupplierPriceForm supplierId={id} supplierMaterialId={item.id} /><div className="mt-2 flex justify-end gap-2"><Button variant="ghost" size="sm" asChild><Link href={`/suppliers/${id}?editCatalog=${item.id}`}>Edit catalog entry</Link></Button><ArchiveSupplierMaterialForm supplierId={id} catalogId={item.id} /></div></div>}
        </article>; })}</div>}</section>

    <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-semibold">Purchase history</h2><p className="mt-1 text-xs text-slate-500">{purchaseOrderCount} orders · latest 25 shown</p></div>{!purchaseOrders.length ? <EmptyState compact kind="items" title="No purchase orders" /> : <div className="max-h-[360px] divide-y divide-slate-100 overflow-y-auto">{purchaseOrders.map((order) => <Link key={order.id} href={`/purchase-orders/${order.id}`} className="flex items-start justify-between gap-3 px-6 py-4 hover:bg-slate-50"><div><p className="text-sm font-semibold text-slate-800">{order.po_number}</p><p className="mt-1 text-xs text-slate-500">{order.warehouse_name} · {date(order.ordered_on)} · {order.receiptCount} receipts</p></div><Badge variant={order.status === "received" ? "active" : order.status === "cancelled" ? "neutral" : "review"}>{order.status.replaceAll("_", " ")}</Badge></Link>)}</div>}</article><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-semibold">Supplier history</h2><p className="mt-1 text-xs text-slate-500">Append-only supplier, catalog, and price events</p></div>{!events.length ? <EmptyState compact kind="items" title="No history available" /> : <div className="max-h-[360px] divide-y divide-slate-100 overflow-y-auto">{events.map((event) => <div key={event.id} className="px-6 py-4"><p className="text-sm font-medium">{event.summary}</p><p className="mt-1 text-xs text-slate-400">{event.actorName} · {dateTime(event.occurred_at)}</p></div>)}</div>}</article></section>
  </>;
}
